import pathlib
p = pathlib.Path('SRJ_FlowNexus_Local/06_HANDOFFS/BUILDER_RELAY_COUNCIL_v282-USDJPY-GUARDS2.md')
data = p.read_bytes()
text = data.decode('utf-8')
assert text.count('GLM-B latch') == 1, 'GLM line missing or duplicated'
start = text.index('Reviewer demands from v281')
endmark = '- Blocking items from v281 (Opus-A4 self-clearing, A7 fail-open-no-trace, A17 E6b-no-positive, A19 B7): RULED - abort closes A4; ABORT rows (unconditional via LogAbort) + per-attempt GUARD rows close A7; pre-declared pobreak + B8 close A17; B7 rewritten (adjudicate kills on rows, halt only unattributable) closes A19.'
assert text.count(endmark) == 1, 'blocking line missing or duplicated'
end = text.index(endmark) + len(endmark)
newblock = r'''Reviewer demands from v281, quoted complete with rulings (nothing built on unruled demands):
- Luna-B shared predicate: "The stronger long-term mechanism is a **single shared fresh-HTF-opposition predicate** used both by the existing ORDER census and by the E4b guard. That would remove duplicate counting logic and make "verbatim predicate" structural rather than textual. The relevant touch points would be the E4b insertion at the 8086-8112 site and the existing ORDER calculation at 5117-5146." RULED DEFERRED to a follow-on (new function surface, needs scope word).
- Luna-B three-state: "A better mechanism is a **dedicated anchor-body-break helper** returning a three-state result such as `CLEAN / BROKEN / UNREADABLE`, while preserving the packet's settled fail-open behavior for `UNREADABLE`. That makes the distinction observable instead of collapsing "could not prove a break" into ordinary clean state. The current logic lives entirely in the E4b block at the 8086-8112 region described by the packet. The current walk itself is specified at P087-P106." RULED DEFERRED (new function surface).
- Luna most-important: "Before touching either predicate, I would settle **what "S3.3 kills" means operationally**. If it means "this confirmation attempt is invalid but the armed candidate survives," the current S2WAIT return is coherent. If it means "the candidate is dead," the current E6a disposition is not sufficient. The page currently contains both meanings without resolving them." RULED - kill adopted via existing abort codes (candidate is dead; no S2 remainder).
- Sonnet-B latched side: "latch the POI-relative side once, at the seed bar, before the walk — e.g. compute `e6b_side` from the seed bar's own open/close relative to the anchor at `e6b_seedShift` (a single read, before the `for` loop at `P092`), store it as a fixed bool, and use *that* latched variable as the "behind" gate on every iteration instead of recomputing `e6b_behind` per-bar. Keep the per-bar `crossDn`/`crossUp` test as-is for the actual break detection. This would touch `P088–P105`, adding one small block above the loop and swapping `e6b_behind` inside the loop body from a per-bar recompute to the latched variable. This turns disclosure (3) from "known simplification" into an actual latched-side implementation, and stops the AND from being a no-op." RULED DEFERRED (behavior change needing its own row evidence; plain cross adopted).
- Sonnet-B helper factoring: "factor the antiNow/antiPrev leg-count logic (`C5120–5134` and `P071–P085`) into a single shared helper (e.g. `bool CountHtfAntiLegs(int shift, int want, int &antiOut)`) called from both the ORDER census site and the E6a site. Touches `C5117–5135` and `P068–P086`. Purely a maintenance/drift-prevention change — output is currently identical either way, so no behavior change, no B1–B7 risk." RULED DEFERRED (new function surface).
- Astra-B durability: "Amend P106–P114 so a proven killing event ends that candidate's eligibility. Prefer an appropriate existing terminal/reset mechanism if one exists; the supplied excerpts do not identify which existing abort code would be correct. If the state must remain S2, it needs a candidate-specific invalid latch that prevents subsequent promotion, including P133, and clears only on an authorized new-candidate lifecycle event. Merely retaining the current state is insufficient." RULED - durability via existing aborts (LTF_MISALIGN for flip; new S54_POIBREAK for break; no S2 remainder, no latch needed).
- Astra-B flip tracking: "P068–P086 can preserve the exact census transition predicate while recording that a qualifying post-retest event occurred. A bounded historical scan is an alternative if candidate start time and historical buffer semantics are reliable. Either mechanism can preserve never-aligned candidates that have never suffered a killing transition." RULED - flip kept as print field; standing-opposition gate preserves never-aligned clean candidates (A1 anti=1).
- Astra-B interval: "Amend P089–P103 to use the rule's actual start event, an exact seed-time contract, and the agreed confirmation-bar boundary. Define dynamic versus locked anchor value and equality/gap behavior before changing the inequalities." RULED ADOPTED (exact=true, anchor>0, seed-inclusive/confirm-exclusive stated, equality/gap choices stated).
- Astra-B outcome separation: "Replace the effective boolean-only decisions across P068–P105 with explicit validity status. Unknown evidence should defer promotion if the goal is mandatory settled-rule enforcement; it need not be mislabeled as a proven break or require a new abort code. Add the missing-read reason and first offending bar/value evidence to P109–P113." RULED ADOPTED as evidence fields in the print (flip/opposed/pobreak/bbar/bpx) plus SEED anomaly print; abort on proven kill only (unproved never mislabeled as break).
- Astra-B death grading: "Amend P143–P150 to require independent E6a/E6b attribution and to prove that the same invalidated candidate cannot confirm later or escape through later alignment. Keep broader S3/S4-origin coverage parked under P024 unless the operator authorizes that extension." RULED ADOPTED as B1/B2/B8 (independent attribution + post-kill silence window).
- Opus-B1 standing opposition: "Replace the block condition at P086/P106 with the state boolean your code already defines: `oOpp` / `biasOpposedAtGate` = `antiNow >= 2` (C5141). Keep `flipNewThisBar` as a print field (its correct role, C5135/C5144). Checked against all four evidence rows: A1 `biasAtGate=1` → 0, promotes ✓; A4 `biasAtGate=1` → 0, untouched ✓; 6/04 `biasAtGate=2` → 1, killed ✓; 6/08 `biasAtGate=3` → 1, killed ✓. Strictly safer, passes every row the newness predicate passes, and makes S2WAIT-retain a sound disposition because the block persists while the opposition does. Cost: more EURUSD takes may die under B7, which is diagnostic, not a regression. Touches P068-P086, P106, P109-P113 (print both fields), P018, P143-P144, P149." RULED ADOPTED (gate condition; disposition upgraded to abort per the kill consensus, making the S2WAIT-retain soundness point moot).
- Opus-B2 reorder inside confirm-true: "Evaluate P068-P105 after `IsConfirmationCandle` succeeds at P117, before the state assignment at P121. Then a fired guard is by definition a blocked promotion, one-to-one with a would-be take." RULED ADOPTED.
- Opus-B3 unconditional diagnostic: "Print one row per E4b promotion attempt with `antiNow`, `antiPrev`, `seedShift`, bars walked, and `poiReads`, whether or not the gate fires. Reuse the E4B_GUARD name with a `fired=` field, or add `E4B_GATEDIAG`. Touches P106-P115 plus one new print-name entry at P138." RULED ADOPTED as E4B_GUARD on every confirm-true with flip/opposed/pobreak/bbar/bpx fields (clean promotions print zeros; fired state derivable).
- Opus-B4 breaking bar: "Carry `e6b_s`, `iTime(...,e6b_s)`, `e6b_v`, `e6b_o`, `e6b_c` out of the loop at P103 and into the print at P109-P113. Makes B1's pobreak leg adjudicable post-run." RULED ADOPTED.
- Opus-B5 seed sanitation: "At P089: require `g_anchorBarTime > 0`, use `iBarShift(..., true)` or validate the resolved time against `g_anchorBarTime`, cap `seedShift - barShift` at a stated maximum, and print an anomaly row on `seedShift < barShift` or cap-exceeded instead of silently skipping." RULED ADOPTED except the lookback cap (REJECTED: a bar-count cap needs a number, prohibited by spec section 0; walk bounded by real seeds only; anomaly print on unresolvable seed).
- Opus-B6 behind term: "Delete P099 (behavior-identical, one less line to defend), or latch the side once at the seed bar and test `behind` against that, which is a genuine gate and a genuine behavior change needing its own row evidence. Do not keep a no-op term described in a disclosure as if it were doing work." RULED - delete ADOPTED; latch DEFERRED (behavior change needing row evidence).
- Opus-B7 parked S3/S4 insertion site: "the LTF invariant block at C7119-C7130 already runs for `ST_S3_ZONE_WAIT..ST_S5_GATE_CHECK`, already holds a `CheckLtfAlign` + `GoAbort`, and is exactly the block E4b bypasses (P013). Naming it now costs nothing and gives the parked item a single site instead of a re-survey next round. Note in P019/P024 only; no edit this round." RULED NOTED in packet scope prose; no edit this round.
- Opus-B8 retain-print helper: "One helper emitting the S2WAIT row with a cause argument (`LTF_UNALIGNED` / `E4B_GUARD`), called from both P114 and P130. Removes the duplicated literal and makes guard kills separable in the journal without a second grep." RULED DEFERRED (new function surface; abort removed the E6 S2WAIT copy, only the original remains).
- Blocking items from v281 (Opus-A4 self-clearing, A7 fail-open-no-trace, A17 E6b-no-positive, A19 B7): RULED - abort closes A4; ABORT rows (unconditional via LogAbort) + per-attempt GUARD rows close A7; pre-declared pobreak + B8 close A17; B7 rewritten (adjudicate kills on rows, halt only unattributable) closes A19.'''
assert "'''" not in newblock, 'quote collision'
assert 'GLM' not in newblock, 'GLM leak'
scrubbed = newblock.replace('iTime(...,e6b_s)', 'ITIME').replace('iBarShift(..., true)', 'IBARSHIFT')
assert scrubbed.count('...') == 0, 'ellipsis leak beyond two source-faithful forms'
new_text = text[:start] + newblock + text[end:]
new_text = new_text.replace('\n', '\r\n')
p.write_bytes(new_text.encode('utf-8'))
out = new_text
print('GLM-refs=', out.count('GLM'))
print('ellipsis=', out.count('...'))
print('V281-lines=', out.count('V281'))
print('bytes=', len(new_text.encode('utf-8')))
