import pathlib
p = pathlib.Path('SRJ_FlowNexus_Local/06_HANDOFFS/BUILDER_RELAY_COUNCIL_v283-USDJPY-GUARDS3.md')
data = p.read_bytes()
text = data.decode('utf-8')
startmark = 'Reviewer demands from v282'
endmark = 'Verification split:'
assert text.count(startmark) == 1, 'start anchor wrong'
assert text.count(endmark) == 1, 'end anchor wrong'
start = text.index(startmark)
end = text.index(endmark)
newblock = r'''Reviewer demands from v282, quoted complete with rulings (nothing built on unruled demands):
- Luna-Q1 structural: "The numerical predicate is the same on readable data, but the implementation does not literally follow that adopted mechanism." RULED - extensional-equivalence proof offered as v283 Q1 (identical reads/shifts/formula/convention; only variable scope differs); literal shared helper DEFERRED (new function surface, needs scope word).
- Luna-A1 P031 contradiction: "P031 says old 27 → new 105, NET +78; the packet header and S3 say old 27 → new 76, NET +49, total +52, post 11604. Those cannot all describe the same edit. This is material because STAGE-1 is explicitly exact-diff/line-count gated." RULED - genuine defect; header corrected to 76/+49 in v10 (S3 already correct); battery now checks every typed number including headers.
- Luna-A2 duplication: "The packet itself records shared-predicate/helper factoring as deferred, but that leaves two independently maintained implementations of the same HTF count: C5117-C5134 and P073-P090. That is the main long-term drift point." RULED DEFERRED (recorded drift; no behavior delta).
- Luna-A3 HTF-unreadable collapse: "HTF read failure is not distinguishable from a clean non-opposed state in the E4B evidence. `e6a_antiNow` remains `-1` if the three reads fail; `e6a_block` then becomes false, while the print emits only `opposed=0`. Thus `opposed=0` can mean either "0/1 opposing legs" or "HTF evidence unreadable." The same issue affects `e6a_flip`. That weakens the claimed adjudicability of fail-open cases." RULED ADOPTED as raw fields (antiNow/antiPrev print -1s, adjudicable).
- Luna-A4 POI-unreadable collapse: "POI unreadability is likewise collapsed into `pobreak=0`. The walker silently `continue`s on failed/empty POI reads. If every intervening bar is unreadable/empty, the final row is indistinguishable from a genuinely clean walk because there is no unreadable count/status in `E4B_GUARD`. This is especially relevant because the prior outcome-separation ruling specifically called for unknown evidence to remain observable rather than look clean." RULED ADOPTED as walked/skipped counters in the print.
- Luna-A5 inverted order: "The code only anomalies `seedShift < 0`; otherwise it walks only when `seedShift > barShift`. Therefore both `seedShift == barShift` and the temporally inverted `seedShift < barShift` fall through to promotion. The packet explicitly says equality is intentionally silent, but it does not explain or diagnose the inverted case. The prior B5 demand had specifically identified that relation as something to anomaly rather than silently skip." RULED ADOPTED as SEEDORDER tripwire (equal stays silent by ruling).
- Luna-A6 anchor wording: "The rule prose says "exact seed with anchor>0," while the implementation checks `g_anchorBarTime > 0`, not `g_anchorLine > 0`. That may be the intended meaning, but the packet should say "anchor-bar-time > 0" explicitly so the rule cannot be read as a price-level validity test." RULED - prose fixed to anchor-bar-time.
- Luna-A7 grader discretion: "B7 still contains a grader-discretion phrase. "Genuine flip/break," "unattributable kill," and "no genuine cause" are not operationally defined in the acceptance text. The packet gives the observable fields, but not the exact adjudication predicate tying those fields to "genuine." That can create a post-run interpretation gap." RULED ADOPTED as mismatch rule + evidence-field semantics in acceptance.
- Luna-B shared helper: "For the durable design, the strongest mechanism remains the already-deferred **shared HTF-opposition predicate/helper** used by both ORDER and E4b, eliminating duplicate counting logic; the packet itself records that proposal and the exact touch points." RULED DEFERRED (new function surface, needs scope word).
- Luna-B three-state: "For E6b, the deferred **three-state break result (`CLEAN / BROKEN / UNREADABLE`)** is the cleanest way to distinguish a proven no-break from insufficient POI evidence without falsely treating unreadable data as clean." RULED DEFERRED (new function surface).
- Luna-B hardening: "Within the current no-new-helper scope, the most useful low-scope hardening would be to add explicit HTF/POI read-status fields to `E4B_GUARD` and diagnose `seedShift < barShift`; those would improve adjudication without changing the settled kill predicate." RULED ADOPTED as raw fields + SEEDORDER tripwire.
- Sonnet Q1 naming: "the Task-76 comment amendment (P155–156) calls the new kill an "E4b-guard **flip** kill," but the gate variable is `e6a_block` (standing opposition, P092), not `e6a_flip` (P091, explicitly print-only per this same packet's own claim). That's a naming inconsistency between P072 ("standing opposition") and P155–156 ("flip kill") describing the identical mechanism." RULED - renamed opposition-kill with two emitters.
- Sonnet Gap-1 ordering: "the anomaly print only covers `e6b_seedShift < 0`. The middle case `0 <= e6b_seedShift < barShift` (seed bar temporally *after* the confirm bar — a genuine ordering anomaly, same class Opus-B5 flagged) falls through both P099 and P104's conditions silently, with no print at all — not even the "silent by design" case the packet documents (P019 only describes the *equal*-shift case as intentionally silent)." RULED ADOPTED as SEEDORDER tripwire.
- Sonnet Gap-2 behind-delete basis: "I can't independently confirm "behind term deleted" as an edit against v1's actual draft, since v1's E6b code isn't reproduced anywhere in this packet — the "old" block shown (C8086–C8112 / P033–P059) predates any guard and never contained a behind term. This claim rests on the packet's own assertion, not a visible before/after in what's pasted here." RULED - correct by exact-diff discipline (v9 packet carried the term with the no-op proof; v10 drops it; STAGE-1 diffs v10 against the built tree, never against v9 prose).
- Sonnet-A1 P031: "**Line-count self-contradiction.** P031 states "(old EA 8086-8112 27 lines, new 105 lines, NET +78)". The actual pasted block (P061–P136) is 76 lines, matching the top-of-packet header ("E4b old 27 / new 76 / NET +49") and the S3 budget (P162: "E4b +49 (76-27)"). P031's own parenthetical is wrong; everything downstream (total +52, post-11604) is consistent with 76/+49, not 105/+78." RULED - header corrected (note: P-numbers shifted in v10; the contradiction was header-vs-blocks, fixed).
- Sonnet-A2 HTF fail-open: "**Fail-open/no-trace in E6a.** If any of the three `ReadFlow` calls fails at `barShift` or `barShift+1` (P076/P084), `e6a_antiNow`/`e6a_antiPrev` stay at `-1`. `e6a_block = (antiNow>=2)` (P092) evaluates false, so an unreadable HTF read promotes exactly like a genuinely aligned one, and the P118 print shows `opposed=0` — indistinguishable from a true zero. No SKIP/anomaly print exists for this case (contrast with E6b's explicit SEED anomaly)." RULED ADOPTED as raw antiNow/antiPrev fields (-1s adjudicable).
- Sonnet-A3 E6b fail-open: "**Fail-open/no-trace in E6b.** Any unreadable POI read inside the walk silently `continue`s (P109). If every bar across the whole seed-to-confirm span is unreadable, `e6b_broken` stays false and the row prints `pobreak=0` — indistinguishable from a genuinely clean walk. No count of bars actually read vs. skipped is carried into the print." RULED ADOPTED as walked/skipped counters.
- Sonnet-A4 ordering: "**Undocumented ordering case** — see Q2 Gap 1 above (P099/P104)." RULED ADOPTED as tripwire (same as Gap-1).
- Sonnet-A5 attribution collision: "**Attribution collision.** When `e6a_block` and `e6b_broken` are both true on the same bar, only `ABORT_LTF_MISALIGN` fires (P119 returns before P120 is reached). The GUARD row at P118 still carries both `opposed=1` and `pobreak=1` — fine, just flagging that any later per-guard tally has to parse those fields rather than count rows." RULED - GUARD-row pairing documented as the grade procedure (abort rows never read alone).
- Sonnet-A6 comment: "**Comment inconsistency** — see Q1 discrepancy (P072 vs P155–156)." RULED renamed.
- Sonnet-B1 HTF SKIP: "Split E6a's `-1` (unreadable) state out from the `<2` (aligned) state explicitly, with its own `E4B_GUARD_SKIP reason=HTF` print, rather than folding "can't read" into "not opposed." Touches P073–P092, P117–P119." RULED ADOPTED as raw -1 fields (no separate SKIP line; unreadable adjudicable in-row).
- Sonnet-B2 walked counters: "Add a walked/skipped-bar counter (`e6b_read`, `e6b_skipped`) to the E6b loop and print both, so a fully-unreadable walk is visibly distinct from a genuinely clean one. Touches P094–P116, P118." RULED ADOPTED as walked/skipped fields.
- Sonnet-B3 tripwire extend: "Extend the seed-anomaly branch to also fire on `0 <= e6b_seedShift < barShift`, not just `<0`. Touches P099–P105." RULED ADOPTED as SEEDORDER tripwire.
- Sonnet-B4 P031 correct: "Correct the P031 parenthetical to 76/+49 to match P162 and the header (documentation-only, no code touch)." RULED - header corrected (note: v10 renumbered; the contradiction was header-vs-blocks).
- GLM-A1 P031: "P031 line-math is wrong. "old EA 8086-8112 27 lines, new 105 lines, NET +78" — the new block P061-P136 is 76 lines, NET +49, as P162 and the relay header correctly state." RULED - header corrected.
- GLM-A2 ORDER-pair labels: "those values are biasAtGate(=antiNow)/opposed (PN/HJ/RE/RF). The flip values are 0/1/1/0. Label should read "bias/opposed."" RULED - v10 authority uses bias/opposed labels with flip values stated separately.
- GLM-A3 comment wording: ""an E4b-guard flip kill" mislabels the gate" and ""the string is now unambiguous" is no longer literally true." RULED - renamed opposition kill with two emitters named.
- GLM-A4 tripwire scope: "a resolved seed with 0 <= seedShift < barShift (seed newer than confirm — should be impossible, which is why the tripwire was demanded) is silently ignored at P104's else." RULED ADOPTED as SEEDORDER tripwire (equal-shift silence kept by ruling).
- GLM-A5 token collision: "`E4B_GUARD` is a substring of `E4B_GUARD_SKIP`." RULED - S1 states trailing-space boundaries with SKIP subtracted.
- GLM-A6 unreadable-vs-clean: "the row prints flip=0 opposed=0 — byte-identical to a clean A1-style row." RULED ADOPTED as raw fields (-1s adjudicable; ORDER-row cross-check documented).
- GLM-A7 mismatch rule: "neither states what happens if the grade observes the opposite." RULED ADOPTED as global mismatch clause (halt with attribution).
- GLM-A8 B2 symmetry: "B2 has no pobreak clause while B1 does." RULED - B2 notes E6a-primary with pobreak adjudicated, not pre-declared.
- GLM-A9 durability assertion: "rests on GoAbort semantics; only LogAbort is excerpted." RULED - noted as grade-tested assumption with B8 post-kill silence window.
- GLM-A10 sentinel: "With e6b_bt=0, P118 prints `bbar=1970.01.01 00:00`, not a zero." RULED ADOPTED as epoch-sentinel clause.
- GLM-A11 insertion-site naming: "P026 parks the S3/S4 extension but never names EA 7119-7130." RULED - scope prose now names the surveyed site (no edit this round).
- GLM-A12 159.929: "appears nowhere on the page." RULED - pasted in v283 rows fence from the MTEXIT row (1x verified).
- GLM-A13 WAIVED-x2: "has no matching excerpted row." RULED - pasted as count-2 pair with pass-time prefix in v283 rows fence.
- GLM-A14 spec text: "S5.4's own text is not on the page." RULED - noted; ruled against packet paraphrase + his finding by reference per verification split.
- GLM-A15 dynamic anchor: "define dynamic versus locked anchor value." RULED ADOPTED as dynamic-anchor clause (per-bar POI buffer read, not locked).
- GLM-A16 mojibake: "C318 contains mojibake." RULED - pre-existing, outside all anchors, noted for carry-check.
- GLM-B1 raw fields: "Add `antiNow`, `antiPrev`, `seedShift`, and walked-bar count." RULED ADOPTED (plus skipped count).
- GLM-B2 tripwire branch: "After P104's `else if(e6b_seedShift > barShift)`, add `else if(e6b_seedShift >= 0)` emitting the existing `E4B_GUARD_SKIP` shape with `reason=SEEDORDER`. Three lines, P104 region only; equal-shift silence stays untouched per P019." RULED ADOPTED (equal excluded from the branch).
- Blocking items from v282 (Luna-Q1 structural; Sonnet naming/gaps; GLM items): RULED as above per item; Luna-Q1 equivalence proof asked as v283 Q1.
'''
assert "'''" not in newblock, 'quote collision'
assert newblock.count('...') == 0, 'ellipsis leak'
new_text = text[:start] + newblock + text[end:]
new_text = new_text.replace('\n', '\r\n')
p.write_bytes(new_text.encode('utf-8'))
out = new_text
print('GLM-refs=', sum(1 for x in out.splitlines() if 'GLM' in x))
print('ellipsis=', out.count('...'))
print('bytes=', len(new_text.encode('utf-8')))
