$ErrorActionPreference = 'Stop'
$src = 'SRJ_FlowNexus_Local/01_TASKS/PACKET_P-RECON74FIX-2v38.md'
$dst = 'SRJ_FlowNexus_Local/01_TASKS/PACKET_P-RECON74FIX-2v39.md'
$a = [IO.File]::ReadAllLines((Resolve-Path $src))
if ($a.Length -ne 184) { throw "source lines=$($a.Length)" }
$sourceHash = (Get-FileHash -LiteralPath $src -Algorithm SHA256).Hash
if ($sourceHash -ne '323C1259F2CF8B3F9F49A631ADF95478A2D1C505B7E81A5544783F282A6C6E0E') { throw "V38 input hash mismatch: $sourceHash" }
$physicalMap = @{}
for ($i=0; $i -lt $a.Length; $i++) { $physicalMap[$i+1] = $i }
foreach ($n in 1..184) { if ($physicalMap[$n] -ne ($n-1)) { throw "Physical P-line map failed at P$n" } }
if ($a[0] -ne '# PACKET_P-RECON74FIX-2 v38 DRAFT - V387 page-only fold; EA code unchanged' -or $a[21] -ne '## Settled-rules audit (RULES-COMPLETENESS output; seedBiasAl baseline census 10 occurrences on 9 lines)' -or $a[109] -notlike '## Acceptance (*' -or $a[169] -ne '## Fold map (V387 dispositions of V386; v37 remains predecessor)' -or $a[183] -ne '(End of file - total 184 lines)') { throw 'Physical section boundaries or anchor map changed' }
if (Test-Path -LiteralPath $dst) {
    $existingHash = (Get-FileHash -LiteralPath $dst -Algorithm SHA256).Hash
    if ($existingHash -ne '22EE2F233F825F7681442BE6E42AF83DFC412B405D84D5341381BBF7BC15EDE0') { throw "Refusing to replace non-generated packet: $existingHash" }
    Remove-Item -LiteralPath $dst
}
$u = @{
1 = '# PACKET_P-RECON74FIX-2 v39 DRAFT - V388 page-only fold; EA code unchanged'
3 = 'Status: v39 DRAFT (V388 replies filed whole and graded separately: Q1 Sonnet conditional CONFIRM / GLM CONFIRM with page fixes; Q2 Sonnet OBJECT / GLM discrepancy graded OBJECT / AMEND-WITH-HALT under section 47. Page-only fold; no EA edit. The 5M-FLIP-KILL pin remains binding; opposite state alone is not established sign-change evidence. Proposed v26 edit set remains proposal-only; EA base 977B0FB597F880C46BEB824937669F863C4452C48A6F9FA506311F04267B414E/684499 bytes/12295 lines. V389 review asks Sonnet and GLM; Astra/Opus optional by operator choice. No separate operator GO/HOLD supplied. No EA edit/build/run/key/commit/push authorized.'
6 = 'Canonical proposal: Experts\SRJ_FlowNexus_EA.mq5 only; v26 fence set carried unchanged through v38. Three inserts + two modified lines; no new inputs, buffers, or handles; indicator and FlowLogic untouched. Proposed only, not authorized. EA cite namespace: unqualified means v29 baseline; P090 marks proposed offsets. Proposed offsets can collide with different v29 meanings; namespace every colliding/proposed cite.'
10 = '- V31 (V381) was behavior round 16; V32 round 17; V33 round 18; V34 round 19; V35 round 20; V36 round 21; V37 round 22; V38 round 23; V39 will be round 24 if transported. V379 packet v29 was round 14 and V380 v30 round 15; v25 and relays V375/V378 untransported. This is a page-only fold of V388.'
11 = '- V381 tallies: Q1 both conditional CONFIRM; Q2 Sonnet OBJECT + GLM CONFIRM = OBJECT / AMEND-WITH-HALT under council section 47. V382: Q1 both conditional CONFIRM; Q2 Sonnet OBJECT + GLM conditional CONFIRM = OBJECT / AMEND-WITH-HALT. V383: Q1 both conditional CONFIRM; Q2 both OBJECT = OBJECT / AMEND-WITH-HALT. V384: Q1 both conditional CONFIRM; Q2 Sonnet OBJECT + GLM conditional CONFIRM = OBJECT / AMEND-WITH-HALT. V385: Q1 both conditional CONFIRM; Q2 Sonnet OBJECT + GLM conditional CONFIRM = OBJECT / AMEND-WITH-HALT. V386: Q1 Sonnet conditional CONFIRM + GLM CONFIRM; Q2 Sonnet OBJECT + GLM CONFIRM = OBJECT / AMEND-WITH-HALT. V387: Q1 Sonnet conditional CONFIRM / GLM CONFIRM with fixes; Q2 Sonnet OBJECT / GLM conditional CONFIRM = OBJECT / AMEND-WITH-HALT. V388: Q1 Sonnet conditional CONFIRM / GLM CONFIRM with fixes; Q2 Sonnet OBJECT / GLM discrepancy = OBJECT / AMEND-WITH-HALT. No separate operator vote-free GO/HOLD accompanied V388; reviewer advice does not substitute.'
19 = '  - CONFIRM-ONCE + TIMING-N/N+1 (s2, verbatim: the latest D POC retest is at 9:35 and then the confirmation candle is the 9:40 and the EA should enter at 9:45 open candle price): 09:40 bar evaluates at the 09:45 pass, entry 09:45 open. N/N+1 convention: floor the tester-time field to M5 equals the bar time plus five minutes; seconds may occur within that timestamp, as P166 specifies.'
24 = '- S5.4 pre-confirmation body-break + S3.3 flip-kill: the S2 CheckLtfAlign gate at EA-8405/8407 is level admission only and does not distinguish 5m-opposite from neutral. The 5M-FLIP-KILL pin at P016 remains binding. This packet does not claim the unchanged edge edit proves the pin; Q1 remains conditional/run-graded at P094. A demonstrated pre-confirmation sign-change is a PIN-VIOLATION/FAIL under P112/P123-P126; opposite state without prior mapped 5m value is UNPROVEN/HOLD.'
25 = '- The new disjunct executes only when aligned is false, so opposite-ltf promotion is possible by construction; EA-8417@v29 ltf prints a state, not a veto or sign-change. The pin means a 5m-structure-bias sign-change before confirmation. FL_BUF_LTF_BIAS mapping to that structure and the prior 5m value are not exhibited here; absent both, pin status is UNPROVEN/HOLD. No edge guard is included; run grading cannot call opposite state a proven flip.'
30 = '- 8-June keep + never-reseeded keep: unset kills persist. Acceptance requires the pinned 8-June negative control at P137 and the 6/9 never-reseeded 09:50 keep at P142. P138-P141 are Weekly-VWAP regression diagnostics only; they cannot independently clear.'
31 = '- EU sibling check: no August run on this packet (structural fence). EU takes-move watch rides a future word plus key scope, never this run.'
38 = '    - Verdict history: V374 Q1 2 CONFIRM / 1 OBJECT; Q2 1 CONFIRM / 2 OBJECT. V376 Q1 Luna OBJECT, Sonnet CONFIRM, GLM CONFIRM = 2 CONFIRM / 1 OBJECT (V376-GRADE records OBJECT-first tally 1-2); Q2 0 CONFIRM / 3 OBJECT. V377 Q1 1 CONFIRM / 2 OBJECT; Q2 0 CONFIRM / 3 OBJECT. V379 and V380 separately graded Q1 conditional CONFIRM / Q2 OBJECT; V381-V385 dispositions are in versioned folds; V386 Q1 conditional/split CONFIRM / Q2 OBJECT-AMEND-WITH-HALT; V387 Q1 split CONFIRM with fixes / Q2 OBJECT-AMEND-WITH-HALT; V388 Q1 split conditional CONFIRM / Q2 OBJECT-AMEND-WITH-HALT. V378 was not transported, zero markers.'
43 = '- B1 chain (5 June London USDJPY SHORT, his frame: retest 09:35 bar, confirmation 09:40 bar, entry 09:45 open 159.948 R2.00 TP 12:15): 09:05 KILL (R01, stale 6/4 SHORT value per R02) + 09:15 reseed (R03, SHORT; same-pass edge g_dir agrees per R05; R01 is the cross-pass 09:05 event) + kills 09:15/09:30/09:35 (R04/R06/R08) with values (R05/R07/R09) + CONFIRMPOLL 09:35 confirm=0 shadow poll (R10, not live-path evidence and not a 09:40 negative) + 09:40-bar absent run-wide by disk assertion (dead seed); it is not a carried-row exhibit. R03 al=0/ok=1 means unaligned-or-neutral, never flip-proven. Same-pass tie-break by journal line number is disk/runtime context, not page-exhibited proof. v26 reference is foreign-build hypothesis only. The interim LONG holder observation is not treated as a second candidate or take; candidate membership is governed by future same-chain evidence under P117-P119. Row listing is not event print order: where both prints occur, UJPROV (EA-8412@v29) precedes KILL (EA-8419@v29); R01/R02 and R04/R05 preserve row IDs, not chronology.'
44 = '    - 8-June keep (invalid pinned London SHORT candidate, never a take): pinned identity is date + symbol + direction + setup-chain keyed by poi and session; only matching candidate is London 09:25 Weekly-POC (disk-asserted; KILL/UJPROV rows do not print sess). R11/R12 together are its 09:25 control evidence. R25-R28 are separate Weekly-VWAP regression diagnostics under P030, not identity evidence and not required negative-control cells. The pinned candidate requires no matching admission at any bar. At the 09:25 control, any exempt=1 paired with same-bar S2PROMOTE_M15 is NEGATIVE_CONTROL_BREACH / M FAIL and T FAIL, regardless of reseedBar; stamp attribution changes only the explanation. The battery must assert exempt=1 iff S2PROMOTE_M15 is emitted at the same bar; parity mismatch is M FAIL. With unset reseedBar require KILL, exempt=0, and no promotion. Missing required evidence is UNRESOLVED/HOLD. No blanket ban on unrelated 6/8 SHORT setup-chains and no flip attribution are inferred.'
45 = '- Direction keeps (disk-asserted take-list classification; forecasts only): 6/5 16:00 LONG and 6/11 14:45 SHORT are not-fired mismatched-row cases (R17/R18; R22/R23; 6/11 10:35 LONG reseed per R21); fired-branch outcomes after clears are unknown. P136/P154 outcomes are conditional forecasts; grade each actual branch UNRESOLVED unless its required arm/holder evidence is established. Fallback mismatch proof bars are only 6/10 15:45 and 17:10 LONG, subject to P151/P152 conditions. 6/12 10:55/18:10 remain UNRESOLVED under P116/P158/P162 and are not fallback proof.'
49 = '## Edit set (exact anchors; STAGE-1 source census stated per symbol; 3 inserts + 2 modified lines; duplicate statements consolidated; convention: NET per site = new minus old)'
59 = '    - FIX DIR-SET (H1 post-overwrite, after CARRY set EA-7899; one insert after EA-7899; SET order: EA-7885 precedes SET in the same H1 branch; R03/R05 show same-pass agreement but do not exhibit g_dir at DIR-SET; R03 prints t78_dir, and P026 does not assert resolver return identity. S1C may rewrite g_dir post-SET. Promotion with reseedDir opposite g_dir is structurally excluded by the proposed predicate; same-direction wrong-anchor promotion remains possible per P096. The value stored at SET time is inferred, not row-exhibited. Record reseed direction; no anchor stamp is stored.)'
82 = '  - FIX PRINT-DIR (S2 edge print EA-8412; proposed append reseedDir and exempt flag): exempt=1 names the complete promotion condition, not the arm. P115(1) separately isolates the new disjunct with seedBiasAl=0. Battery must assert exempt=1 if and only if S2PROMOTE_M15 is emitted at the same bar; mismatch fails M. No print/code alteration beyond the shown proposal is included.'
89 = '- Scope: reseedDir declaration/SET/CLEAR remain the v29 proposed sites; g_dir and its writers are carried unchanged. The print flag equals the complete promotion predicate, not an arm discriminator. P115(1) uses seedBiasAl=0 to isolate the new disjunct. The 9-space TERM/PRINT lines are machine-verified against the old 9-space source lines; the 10-space duplicate code copies are removed. SHORT runtime is exhibited; LONG runtime and S2ResolveLive argument identity are not claimed. No edge guard is included.'
90 = '  - Census after proposed edit (proposed-tree/post-edit offsets, not a built tree; every EA number in this sentence is @proposed): reseedDir initialization/write sites EA-304/7901/10730; CARRY reseedBar initialization/write sites EA-303/7900/10729. On unchanged v29 baseline, g_ujOpReseedBarTime has 4 occurrences on 4 lines: initialization EA-303, H1 write EA-7899, observational UJPROV print read EA-8412, and admission clear EA-10727; exact-symbol census shows no additional read/write occurrence or by-ref writer. seedBiasAl occurs 11 times on 9 distinct lines: baseline 10 occurrences/9 lines plus one new occurrence in PRINT-DIR; declaration EA-1155, producers EA-7882/EA-8203, EA-8414 carries three occurrences after the print edit (format, argument, exempt expression), TERM EA-8415, promotion print EA-8419, comment EA-10438, SIDE1R format EA-10445, SIDE1R argument EA-10449. EA-8201@v29 is a second baseline producer outside the carried producer block; whether it pairs with reseedBar/Dir is unproven, so the exemption assumption is not asserted for that producer. These are proposed-tree census claims, not runtime evidence. Only EA lines physically carried in relay regions are page-exhibited; unshown sites prove no runtime behavior. The baseline 10-occurrence split is explicitly the five page-exhibited and five machine-only members listed at P026. The aligned=true continuation after EA-8422@v29 is not carried; parity-take mentions at P122 are disk-asserted, not a path exhibit, and no path-specific claim relies on that continuation.'
96 = '- Same-direction stale churn remains an identity-blindness limit, not an endorsed pass: the 09:05 class is one exhibit. R21 shows dir=LONG/fromDir=SHORT; R24 shows a SHORT holder at 14:35; R23 still prints the 10:35 reseed stamp. These rows exhibit holder-direction change without a stamp change, but do not exhibit the mechanism (S1C at EA-7902-7909@v29 or a fresh seed) responsible. P115''s B3 twin (P155/P156) is conditional on the future branch and stored stamp direction matching the holder; otherwise remain UNRESOLVED pending run evidence.'
97 = '- 6/11 10:35: R21 is a UJRESEED with dir=LONG and fromDir=SHORT, not "LONG on LONG". It does not establish candidate membership or a binding flip; R21 prints t78_dir, not post-resolver g_dir. R21/R23 show poi change to Daily-POC with retained stamp, but not mechanism or DIR-SET value. P117-P119 keep membership UNKNOWN until the future run; older row is context only. P154-P156 forecasts are conditional on the 10:35 reseed being re-established, stored direction matching the holder where required, and future branch evidence; otherwise grade actual branches UNRESOLVED.'
108 = '- EU sibling watch scope is governed by P031; this UJ packet carries no August EU run.'
109 = '- No EU run or EU take is graded in this UJ packet; a future EU check still needs its own word plus key scope.'
110 = '## Acceptance (FIX-2v26 validation on a future UJ 6/1-6/13 run; proposed code edit set unchanged from v26; branch-complete PATH_CLASS with non-clearing unresolved states; 21 behavior rounds through V386; V387 round 22, V388 round 23, V389 round 24 if transported; no new EA code delta)'
112 = '   - Dispatcher and PATH_CLASS (binding order): reject UNEXPECTED_TAKE; freeze each H_STATUS; for any FIRED admission inspect the full same-chain pre-confirmation path and apply the fired-path flip test before branch or edge-presence processing; then select WW/FW/WF/FF, establish edge presence, classify PATH_CLASS, grade axes, and evaluate parity/allowed-set. An S2 edge after first same-chain S2PROMOTE_M15 is OUTSIDE-REQUIRED whether present or absent; it is not graded as a required cell and applicable pin checks still apply. NA-EXCLUDED is reserved for absent-by-design cells. Other absent required edges are UNRESOLVED/HOLD unless exhibited causal evidence assigns DIVERGED or PIN-KILL-EXPLAINED. The binding pin means a demonstrated sign-change in 5m structure bias before confirmation. Printed ltf opposite to trade direction proves opposite state only; it proves a sign-change only with a prior 5m value and a verified FL_BUF_LTF_BIAS-to-structure mapping, neither exhibited here. Without them pin status is UNPROVEN/HOLD. Fired plus established same-chain sign-change is PIN-VIOLATION/FAIL. Positive advancement requires exact emitted S2PROMOTE_M15 bar= or CONFIRM_PREBIND bar= (not CONFIRM_PREBIND_FAIL); UJRESEED/UJPROV alone is not advancement. WITHDRAWN_TERM requires observed ordinary terminal withdrawal before required edge, no advancement and no pin-abort; it is non-clearing. PATH_CLASS excludes FIRED and does not recompute H_STATUS.'
113 = '   - Axes: M grades row mechanics including unauthorized negative-control promotions; T grades take, hypothesis, no-false-take and parity. M PASS and T PASS are necessary, not sufficient, for clearance, which also needs the separately authorized operator-side 5m-series review or newly scoped evidence design and later council review. NA-EXCLUDED cannot satisfy a required edge. UNRESOLVED, PIN-KILL-EXPLAINED, WITHDRAWN_TERM, DIVERGED and unresolved OUTSIDE-REQUIRED pin checks are non-clearing; PIN-VIOLATION and NEGATIVE_CONTROL_BREACH are FAIL (breach fails M and T). FIX is diagnostic/non-clearing. P137 (pinned 8-June) and P142 (6/9 09:50 never-reseeded keep, tied to P030/P046) are the only required negative controls. P138-P141 are Weekly-VWAP regression diagnostics under P030, not required controls and cannot independently clear. Their KILL rows are context; no absent UJPROV/exempt claim is inferred. The battery cannot self-clear: fired B1 can at best be FIRED / no established sign-change / pin status UNPROVEN / HOLD; non-fired owed B1 also holds. Forecasts and absence alone never clear.'
115 = '     - B1 required present edges: (1) reseedDir=-1, seedBiasAl=0, nonzero reseedBar. Require exempt=1 only when row also exhibits m15 read-ok/match; prior R01/R04/R06/R08 establish this only for those bars. Positive confirmation may be CONFIRM_PREBIND bar=09:40 at pass 09:45; negative requires live-path shadow=false CONFIRMPOLL or CONFIRM_PREBIND_FAIL. B3 twin is conditional on stale 10:35 stamp and stored direction matching holder; future rows govern. Non-FIRED owed B1 holds.'
116 = '     - NA-EXCLUDED is only absent-by-design. Post-promotion edges are OUTSIDE-REQUIRED whether present or absent, with applicable pin checks still applying. Forecasts remain non-results; P154-P156 are conditional on re-established 10:35 reseed, matching stored direction where required, and future branch evidence. P158/P162 remain UNRESOLVED absent branch-specific post-clear evidence.'
118 = '  - P-PROMOTE-FIRST: candidate membership is established only from future run rows and chain breaks; prior-build R rows are context only. 6/11 10:35 remains UNKNOWN until that run resolves it; P153 records uncertainty without assigning class. P115(1), not census membership, tests the new disjunct. Forecast class is owned by P117/P119.'
120 = '     - P-KEEP: pinned 8-June identity and only-matching-candidate claim are disk-asserted; KILL/UJPROV lack sess. P137 uses R11/R12. At the required 09:25 control with unset reseedBar require KILL, exempt=0, and no promotion. Any exempt=1 paired with same-bar S2PROMOTE_M15 is NEGATIVE_CONTROL_BREACH / M FAIL and T FAIL regardless of stamp attribution; attribution only explains the breach. Assert exempt=1 iff same-bar promotion on each run row; parity mismatch is M FAIL. A set stamp alone without a promotion does not prove stale-stamp causation; unresolved attribution remains UNRESOLVED/HOLD absent legitimate matching admission. Missing evidence is UNRESOLVED/HOLD. Late Weekly-VWAP bars are regression diagnostics, not same-chain identity. No unrelated 6/8 SHORT ban.'
123 = '  - P-PARITY-FIRED: before parity can clear, inspect every same-chain pre-confirmation path for baseline and hypothesis takes. A printed S2PROMOTE_M15 bar= row with ltf opposite to direction proves opposite state at promotion, not a sign-change and not that a flip-kill emitter fired. Establishing the pinned sign-change requires prior 5m bias plus verified FL_BUF_LTF_BIAS mapping; neither is exhibited, so that pin conclusion stays UNPROVEN/HOLD. LTF_MISALIGN and FRESHCOUNT ABORT alone are not sign-change evidence; if separately evidenced as pin-compliant aborts classify PIN-KILL-EXPLAINED/HOLD, otherwise UNRESOLVED/HOLD. Fired admission plus established same-chain sign-change is PIN-VIOLATION/FAIL.'
124 = '    - P-NOFALSE: UNEXPECTED_TAKE precheck precedes H_STATUS. The pinned-invalid 8-June London 09:25 SHORT cannot be a clearing take; attribution remains UNRESOLVED/HOLD-terminal absent evidence. Any admitted take with an established same-chain pre-confirmation 5m-structure sign-change is PIN-VIOLATION/FAIL. No S5 one-position gate is asserted; per-session cap and cross-session coexistence are grounded in spec Part A v4.2 L283/L291. Ordinary frozen identity: venue, date, direction, admission bar, entry price +/-5 x runtime _Point, plus the actual sess token from the same-candidate S2PROMOTE_M15 or S2WAIT run row. Record runtime _Point and _Digits; do not assume pips or hardcode a symbol precision. Do not take sess from CONFIRM_PREBIND. Match the union of branch identity before branch selection; if the required candidate row has no sess, identity is UNRESOLVED/HOLD. The 8-June negative-control instead uses date + symbol + direction + setup-chain; KILL/UJPROV do not print sess.'
125 = '   - H-TAKE identity 6/5 London SHORT, admission bar 09:45, entry 159.948 +/-5 x runtime _Point (record _Point and _Digits; no pip conversion assumed). H_STATUS follows P114. WITHDRAWN_PIN_ABORT requires an evidenced rule abort and makes no direct-flip causation claim. Opposite-ltf promotion is opposite-state evidence only, not proof of a sign-change. Confirm=0 is NEGATIVE only on the 09:40 confirmation bar at the 09:45 pass with shadow=false, or with an exhibited CONFIRM_PREBIND_FAIL; R10 is the 09:35 shadow poll and is not a negative. No confirm evaluation is NO_EVAL; confirm=1 without admission is BLOCKED. Late-TP at 16:55 is parity-only.'
126 = '   - H-B3TAKE identity 6/11 LONG admission bar 14:40, entry 160.524 +/-5 x runtime _Point (record _Point and _Digits; no pip conversion assumed). Evaluated bar=14:35, pass floor 14:40; R24 is SHORT/shadow=true and is neither LONG life nor a negative. FIRED requires matching admission only; separately require and grade the LONG life row from 10:35 through 14:40 on the M axis. Missing life row makes that axis UNRESOLVED/HOLD. Without admission, classify only on exhibited evidence: no evaluation=WITHDRAWN_NO_EVAL; confirmation negative per P125=WITHDRAWN_NEGATIVE; evidenced rule abort=WITHDRAWN_PIN_ABORT; confirm=1=BLOCKED_NO_ADMISSION. Fired plus established direct same-chain sign-change is PIN-VIOLATION/FAIL. A mismatched take is UNEXPECTED_TAKE. Post-admission absent edges follow P116.'
128 = '    - Arming ledger schema: evaluated bar/date-time | direction | R-row/context or future-run row | arm context (may list alternatives; not branch output) | WW | FW | WF | FF. Column headers: first letter is B1, second is B3; W=admission not fired, F=fired. P=conditional promotion forecast only before first same-chain S2PROMOTE_M15; subsequent same-chain edges are OUTSIDE-REQUIRED whether present or absent, not NA-EXCLUDED. Km=expected direction-mismatch kill. Ku=expected unset-provenance kill only when the FIRST letter is W (B1 not fired) and before B3''s 6/11 14:40 admission; thus pre-6/11 controls forecast Ku in WW and WF, never in FW or FF. The second B3 letter cannot causally alter earlier stamps. F-branch provenance remains UNRESOLVED. P/Km/Ku are forecasts, not PATH_CLASS values, M/T grades, or passes. NA-EXCLUDED is reserved for proven design absence; UNRESOLVED is missing/unknown evidence. At run grade, test actual row predicates; symbols never substitute for output.'
133 = '    06.05 09:15 SHORT R=R03,R04,R05 arm=06.04 10:20/SHORT if first promotion preserves holder; arm=06.05 09:15/SHORT only if R03 reseed fires WW=P FW=P WF=P FF=P (conditional forecast only while before first same-chain promotion; after promotion OUTSIDE-REQUIRED whether edge exists or not)'
134 = '    06.05 09:30 SHORT R=R06,R07 arm follows row-proven 09:15 reseed or carried 06.04 arm WW=P FW=P WF=P FF=P (conditional forecast only while before first same-chain promotion; after promotion OUTSIDE-REQUIRED whether edge exists or not)'
135 = '    06.05 09:35 SHORT R=R08,R09,R10 arm follows row-proven 09:15 reseed or carried 06.04 arm WW=P FW=P WF=P FF=P (conditional forecast only while before first same-chain promotion; after promotion OUTSIDE-REQUIRED whether edge exists or not)'
136 = '    06.05 16:00 LONG R=R17,R18 arm=06.05 09:15/SHORT WW=Km FW=UNRESOLVED WF=Km FF=UNRESOLVED (FW/FF post-admission provenance is unexhibited after B1 consumes CARRY at EA-10727@v29; actual branch is UNRESOLVED absent arm evidence)'
142 = '    06.09 09:50 SHORT R=R19,R20 arm=-/- WW=Ku FW=UNRESOLVED WF=Ku FF=UNRESOLVED; required identity is the 6/9 never-reseeded keep tied to P030/P046; on each run row require S2SEEDBIAS_KILL, UJPROV exempt=0, and no S2PROMOTE_M15.'
143 = '   06.09 10:20 SHORT R=disk-asserted arm=06.09 10:05/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
144 = '   06.09 10:30 SHORT R=disk-asserted arm=06.09 10:05/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
145 = '   06.09 15:35 SHORT R=disk-asserted arm=06.09 15:10/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
146 = '   06.09 15:55 SHORT R=disk-asserted arm=06.09 15:55/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
147 = '   06.09 16:10 SHORT R=disk-asserted arm=06.09 16:10/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
148 = '   06.09 16:15 SHORT R=disk-asserted arm=06.09 16:10/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
149 = '   06.09 17:30 SHORT R=disk-asserted arm=06.09 16:10/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
150 = '   06.10 09:15 SHORT R=disk-asserted arm=06.09 16:10/SHORT WW=P FW=P WF=P FF=P (conditional forecast only if the 6/9 reseed is re-established in the future run; otherwise actual branches UNRESOLVED)'
154 = '    06.11 14:45 SHORT R=R22,R23 arm=06.11 10:35/LONG WW=Km FW=Km WF=UNRESOLVED FF=UNRESOLVED (conditional forecast only if the 10:35 LONG reseed is re-established; WW/FW Km assumes its stored LONG direction meets the SHORT edge as a mismatch; otherwise actual branches UNRESOLVED)'
155 = '    06.11 16:05 LONG R=disk-asserted arm=06.11 10:35/LONG WW=P FW=P WF=UNRESOLVED FF=UNRESOLVED (conditional on re-established 10:35 reseed, stored direction matching LONG holder, and future branch; otherwise actual branches UNRESOLVED)'
156 = '    06.11 16:25 LONG R=disk-asserted arm=06.11 10:35/LONG WW=P FW=P WF=UNRESOLVED FF=UNRESOLVED (conditional on re-established 10:35 reseed, stored direction matching LONG holder, and future branch; otherwise actual branches UNRESOLVED)'
170 = '## Fold map (V388 dispositions; v38 remains predecessor)'
171 = '  - Q1 V388: Sonnet conditional CONFIRM; GLM CONFIRM with page fixes. Adopt the opposite-state-versus-sign-change distinction; add reseedBar source census; repair P115(1), P059 punctuation, undefined pin/outcome token, P019 timing words, P045 disk-asserted status, +/-5 x runtime _Point, P024/P025 and EU duplicate wording, history labels, and inline forecast conditions. Preserve the accepted run-graded risk and parked code advisories.'
172 = '  - Q2 V388: Sonnet OBJECT; GLM discrepancy -> OBJECT / AMEND-WITH-HALT. M/T PASS necessary not sufficient; migrate every post-promotion cell to OUTSIDE-REQUIRED; parity assert exempt iff same-bar promotion; distinguish opposite state from sign-change; identify P142 as the never-reseeded keep; mark FW/FF at P136 UNRESOLVED; state required-control vs regression criterion; add conditions to P143-P150 and P154-P156.'
173 = '  - Edge veto, CONFIRMPOLL ltf, UJPROV ltf, and per-holder stamp remain advisory/parked. No code proposal adopted; any such work requires its own scope and exact grant words.'
174 = '  - Separate vote-free GO/HOLD was not supplied with V388 and is not inferred. V389 page review required. No EA edit or new run evidence. P104 and code/telemetry changes remain parked; no code action until council clearance and separate exact grant words.'
175 = '  - Builder assembly D14 was caught by disk read-back before transport, repaired, and recorded at ledger 1090. Physical P-line/index mapping and whole-section read-back are required by the council skill. No EA/source change.'
177 = '     ## Budget recount: proposed DIR-DECL +1 / DIR-SET +1 / DIR-CLEAR +1 / EXEMPT-TERM +0 / PRINT-DIR +0. NET +3 vs v29 EA tree 12295; final proposed 12298. V39 page only; no EA delta.'
182 = '      - Novel page evidence vs V387: complete fresh V388 Sonnet and GLM replies plus their Q1/Q2 findings only; no new runtime evidence. Packet preserves unresolved source mapping, sign-change proof, census membership, future-run branches, and unknown branch-specific arms.'
}
foreach ($k in $u.Keys) {
    $idx = [int]$k - 1
    $a[$idx] = $u[$k]
}
$bytes = [Text.UTF8Encoding]::new($false).GetBytes(($a -join "`n") + "`n")
[IO.File]::WriteAllBytes((Join-Path (Get-Location) $dst), $bytes)
$saved = [IO.File]::ReadAllLines((Resolve-Path $dst))
$text = [Text.UTF8Encoding]::new($false).GetString([IO.File]::ReadAllBytes((Resolve-Path $dst)))
if ($saved.Length -ne 184 -or $text.Contains("`r") -or $text.Contains('...') -or $text -match '[^\x00-\x7F]') { throw 'v39 format gate failed' }
foreach ($k in $u.Keys) { if ($saved[[int]$k - 1] -cne $u[$k]) { throw "Saved line P$k mismatch" } }
"V39 saved; sha=$((Get-FileHash $dst -Algorithm SHA256).Hash); bytes=$($bytes.Length); lines=$($saved.Length); modifiedP=$($u.Count)"
