# pktv36draft.ps1 - DRAFT v35-to-v36 packet amend (ASCII-only script; asserts + in-place line replaces; NO EA edit, NO build, NO run)
$ErrorActionPreference = 'Stop'
$Pkt = 'C:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\01_TASKS\PACKET_EXT1LIVE-001.md'
$EA = 'C:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\Experts\SRJ_FlowNexus_EA.mq5'
$raw = [IO.File]::ReadAllBytes($Pkt)
$hasBom = ($raw.Length -ge 3 -and $raw[0] -eq 0xEF -and $raw[1] -eq 0xBB -and $raw[2] -eq 0xBF)
"PRE_BOM=$hasBom"
$text = [Text.Encoding]::UTF8.GetString($raw)
$crCount = ($raw | Where-Object { $_ -eq 13 }).Count
if ($crCount -ne 0) { throw "CR found $crCount" }
if ($raw[$raw.Length - 1] -ne 10) { throw 'no trailing LF' }
"PRE_LF_ONLY=true PRE_TRAIL_LF=true"
$pre = [IO.File]::ReadAllLines($Pkt)
if ($pre.Count -ne 58) { throw "count $($pre.Count)" }
"PRE_LINES=58"
$preHash = (Get-FileHash -LiteralPath $Pkt -Algorithm SHA256).Hash
if ($preHash -ne '22475D22971B87A0040942F3D7B09C482CE33E7023A7BB3E9D9CB2FAC0CA5E0F') { throw "pre-hash drift $preHash" }
if ($raw.Length -ne 165814) { throw "pre-bytes drift $($raw.Length)" }
"PRE_HASH_OK=22475D22 PRE_BYTES=165814"
$heads = @{0='# PACKET_EXT1LIVE-001 v35 DRAFT'; 2='Status: AUTHORED-unbuilt. Nothing builds'; 4='## 1. Rule (FUTURE live-activation seman'; 6='For a DEFINED ext1, no positive-imbalan'; 8='Replacement semantics (FUTURE relay, not'; 10='Ext1-undefined fallback: retain the exi'; 12='Standing rule, not an exception: SESSIO'; 14='## 2. Must-reproduce-or-explain table (P'; 19='| 08-28 16:20 SHORT (A1 declined) | 1.1'; 24='| 09-08 16:40 SHORT (A3 declined) | 1.1'; 27='R-gate constant 1.0 (EA L57 compiled de'; 29='## 3. Probe form (print-only = no strat'; 33='slLive, gateConst, currentPrice, and ac'; 35='Field definitions (diagnostic, not a va'; 37='Pre-build gates (STAGE-0/1, halt-with-d'; 39='## 4. Acceptance (grade lines; actual p'; 41='Actual-path baseline: 7 TP_ELECT fire r'; 45='Monotone-adverse-only adoption stays a '; 47='## 6. Goal layer (v32 - lot-floor proof'; 49='D1 lot-floor proof print (NEW pure inse'; 53='D3 16:45 live-activation (FUTURE rule, N'; 55='D4 8/28 exit-layer join (no new code - '; 57='STAGE-0/1 and novel evidence (halt-with'}
foreach ($k in $heads.Keys) {
  if (-not $pre[$k].StartsWith($heads[$k])) { throw "head L$($k+1)" }
}
"PRE_DRIFT_OK=23 lines"
[string[]]$lines = $pre.Clone()
function Assert-Ascii($s, $tag) {
  foreach ($ch in $s.ToCharArray()) { if ([int]$ch -gt 127) { throw "nonascii $tag U+$(([int]$ch).ToString('X4'))" } }
}
function Count-Hits($line, $old) {
  return ([regex]::Matches($line, [regex]::Escape($old))).Count
}
function Rep1($idx, $old, $new, $tag) {
  Assert-Ascii $old "old-$tag"; Assert-Ascii $new "new-$tag"
  $c = Count-Hits $lines[$idx] $old
  if ($c -ne 1) { throw "hits!=1 $tag L$($idx+1) count=$c" }
  $lines[$idx] = $lines[$idx].Replace($old, $new)
  "REP_OK $tag"
}
# ---- full-line rewrites (7) ----
$lines[0] = @'
# PACKET_EXT1LIVE-001 v36 DRAFT - live the ext1 stop (LIVE activation E-hunk) + USD envelope + goal layer (v36 folds Luna-V198-1-7 (P050 post-floor wording adopted in L50; run-scoped volStep premise plus disclosed G2 non-exhaustiveness plus G4 completeness boundary recorded; DIR_NONE domain plus ext1 metadata closed by the E-hunk) plus Sonnet-V198 close (10:45 row verified whole, nothing open) plus GLM-V198-residuals-1-5 (L1 banner precision; L56 parenthetical; L56 exit-bar check; L58 question citation; L56 flag context) as text (same-session advisory, no clearance claimed); v36 amends v35 (23 lines: L1 version register; L3 live scope plus USD envelope; L5 live header; L7 live rule with P046 guard inline plus domain conjunct plus s1x_sel=2 metadata plus B-kept disposition; L9 E-hunk old/new verbatim; L11 ext1-arm note; L13 A3-decline superseded; L15 live predictions; L20 A1 runtime R; L25 A3 runtime kill; L28 live source-changed bars plus liveSel=2 plus A3/A2 live notes; L30 live-form header; L34 liveSel domain plus live-write note; L36 wouldAdopt-0 on sel=2; L38 E-hunk gates plus USD ini plus slRef-write exception; L40 runtime acceptance header; L42 6-fire baseline; L46 B-7 adopted plus v198 dispositions; L48 v36 goal header; L50 post-floor wording plus USD G1; L54 D3 runtime rule plus runtime G3; L56 GLM-2/3/5 plus G4; L58 pre-hash 7C247F45 plus E-hunk exact-diff plus USD envelope plus v36 novelty plus adherence); A/B/C/D1/D2 literals unchanged, tags stay -v28/-v32; new E-hunk carries tag -v36); v35 folds Sonnet-V197-P056 plus GLM-V197-residuals-1-7 plus Luna-V197-A as text with v35 amending v34 text-only (P032 word landed, per-instance ranges, failure-rule order, POI fix, 8-row ack, adoption-site word), no literal change, tag -v32 (earlier folds ride v35 L1 under 22475D22971B87A0040942F3D7B09C482CE33E7023A7BB3E9D9CB2FAC0CA5E0F); A/B/C literal unchanged, tag -v28 for A/B/C; D1/D2 insertions carry tag -v32)
'@
$lines[2] = @'
Status: AUTHORED-unbuilt. Nothing builds or runs on this file. Clearance + fresh word come only via relay. This authorization, if granted, clears the section-3 LIVE E-hunk (current EA L9663-L9667 old-verbatim to new-verbatim pasted at L9, tag -v36, sole new live write slRef at the former selector site with fallback five statements effect-identical, B L9668 unchanged) PLUS the carried section-3 A/B/C and section-6 D1/D2 print-only instrumentation (literals unchanged from v32, tags stay -v28/-v32, STAGE-1 re-checks all at build) PLUS one run RECON50-EXT1LIVE-V36 under the RECON50_DEMO_USD envelope - never the side-owner site, never the exit model, never the seed mechanism, never any other change. The section-6 goal diagnostics cleared here are: E-hunk live adoption (L9) plus D1 LOTDIAG pure insertion after EA L10109 in v32 wording with rawLots plus belowMin (post-floor wording) plus D2a wrap of EA L7681 plus D2b wrap of EA L7699 plus D2c insertion before EA L7696 plus D4 exit-layer join, as pasted at P050/P052/P056, tag -v32, exact-diff gated. This version is submitted for clearance against received review material (Luna-V198-001 ACCEPT key-1 plus Sonnet-V198 advisory ACCEPT plus GLM-V198-001 ACCEPT on v35 (same-round advisory; dual-key plus run word plus token still owed for v36)); every received request is accounted for as adopted, declined with reasons, or explicitly carried, and only adopted changes form this authorization. v36 withdrawals (retired with successor, LIVE ends here): v35 L3 probe-only scope sentence (successor: this L3 live scope); v35 L5/L7 FUTURE framing (successor: L5/L7 live rule); v35 L9 future-relay semantics (successor: L9 E-hunk); v35 L15 counterfactual predictions (successor: L15 live predictions); v35 L42 7-fire baseline (successor: L42 6-fire baseline); v35 L54 counterfactual D3 (successor: L54 runtime D3); v35 L58 9C79FC1E pre-hash plus JPY envelope plus D3-no-runtime (successor: L58 7C247F45 pre-hash plus USD envelope plus D3-runs-live). Historical register (v29 and earlier withdrawals) rides v35 L3 under 22475D22971B87A0040942F3D7B09C482CE33E7023A7BB3E9D9CB2FAC0CA5E0F, never live constraints.
'@
$lines[4] = @'
## 1. Rule (LIVE activation semantics - the v36 E-hunk executes this rule on the S5 path; probe A/B/C/D carried print-only)
'@
$lines[6] = @'
Live rule (executes on the S5 path under this authorization): for a DEFINED ext1, no positive-imbalance requirement applies; ext1Imb=0 does not disqualify. (The fallback keeps the existing s0 positive-imbalance gate and s1 slot-validity fallback.) At the live-stop select site (current EA L9663-L9667, instrumented tree 7C247F45), when the conjunction (g_dir == DIR_LONG or g_dir == DIR_SHORT) and ext1Defined (g_sl41_def == 1) and finite slExt1 (MathIsValidNumber(g_sl41_px)) and SlimbProtectiveSideOk(g_dir, g_sl41_px, currentPrice) holds, select the candidate-local ext1 price (g_sl41_px, published at L5496-97 from the L8779 S5 call) as slRef with s1x_sel = 2 (ext1-arm metadata, distinct from the 0/1 selector arms and the -1 retain arm; s1x_sel dies at the block close with no live consumer downstream - the sole reader is the carried probe B at L9668, which saves sel=2 with slRef plus the walk s0/s1 carries); otherwise execute the existing five-line selector effect-identical in the else arm (wrapping changes bytes, never effect). DIR_NONE (or any non-LONG/SHORT domain value) falls back by the explicit domain conjunct - the L2580 fallthrough is unreachable on the adopt arm by construction (Luna-V198-5 closed). A defined-but-non-finite (or non-protective, or domain-failed) ext1 takes the fallback selector (fallback-vs-refusal disposition: fallback, frozen here - the live arm never implies a defined-only branch implements this validity requirement). Use the same candidate-local ext1 definition and provenance that supply SLEXT481 (producer locals sl41_def/sl41_px/sl41_slot/sl41_bt/sl41_imb in bool ComputeSlReference at EA L5291, resolved by SrjResolveExt1 at L5326, published to globals g_sl41_* at L5496-97). STAGE-1 carries the named publication obligation plus the finite-predicate 3-result filing plus the dormant-adoption census plus the 168-site debug-input census plus the invocation census, all as filed at v35 L7 under 22475D22971B87A0040942F3D7B09C482CE33E7023A7BB3E9D9CB2FAC0CA5E0F and re-asserted on the instrumented tree at build, else halt. P046 guard adopted inline (Opus-v179 B-7 adopted as the L9 E-hunk; Luna Ask B-3 adopted). Probe-vs-helper equivalence open item is moot for adoption (the live arm calls SlimbProtectiveSideOk itself; the mirror equivalence governs only the reported-never-graded shadow). Ext1-arm metadata open item closed (s1x_sel=2, Luna-V198-6 closed). v33 FLAG retired (side-guard adopted inline here); the P036 helper-equivalence residual is answered as above for the live relay.
'@
$lines[8] = @'
E-hunk (LIVE replacement, tag -v36; replaces exactly current EA L9663-L9667; B at L9668 post-region unchanged; closure L9669; R-gate L9671-L9673; downstream resolution-then-veto-latch-SIGNAL-session chain unchanged): old verbatim (9-space indent): `         int s1x_sel = -1;` + `         if(s1x_s0slot >= 0 && s1x_s0imb > 0) s1x_sel = 0;` + `         else if(s1x_s1slot >= 0) s1x_sel = 1;` + `         if(s1x_sel == 0) slRef = s1x_s0px;` + `         else if(s1x_sel == 1) slRef = s1x_s1px;` - new verbatim (9-space base indent): `         int s1x_sel = -1;` + `         bool ext1Take = ((g_dir == DIR_LONG || g_dir == DIR_SHORT) && g_sl41_def == 1 && MathIsValidNumber(g_sl41_px) && SlimbProtectiveSideOk(g_dir, g_sl41_px, currentPrice));` + `         if(ext1Take) { slRef = g_sl41_px; s1x_sel = 2; }` + `         else` + `           {` + `            if(s1x_s0slot >= 0 && s1x_s0imb > 0) s1x_sel = 0;` + `            else if(s1x_s1slot >= 0) s1x_sel = 1;` + `            if(s1x_sel == 0) slRef = s1x_s0px;` + `            else if(s1x_sel == 1) slRef = s1x_s1px;` + `           }` - counts: 1 new initialized declaration (bool ext1Take); 1 new conditional; ext1 arm 2 assignments; fallback 5 statements effect-identical modulo indent (machine-checked at build); all consumed symbols in scope at the site (g_dir global; g_sl41_def/g_sl41_px globals L1112-L1113 published L5496-97; currentPrice local L8753 single-write; SlimbProtectiveSideOk file-scope L2578; slRef local L8766; s1x_* block locals). Sole new live write: slRef on the ext1 arm (declared and gated here; no other live writes; fallback writes slRef exactly as today). P009 forward-note disposition: the replacement spans exactly L9663-L9667 so the probe B at L9668 sits post-region (not inside it) and stays valid with capture re-proven (probe_sel=2 rows print slLive==pxExt1 with guard plus domain rechecked offline); no re-siting needed, council rules the disposition.
'@
$lines[47] = @'
## 6. Goal layer (v36 - E-hunk LIVE activation + USD envelope + v36 residuals; same window 08-26 to 09-09; RECON49 V35 baseline 7C247F45 carried forward for the carried literals, nothing withdrawn except the v35 counterfactual framing (retired, runtime rules); A/B/C/D1/D2 literals and tags -v28/-v32 unchanged; E-hunk carries tag -v36 for the STAGE-1 gate; LOTDIAG/SEEDDIAG carry no pkt tag (separate Print families); live change confined to the E-hunk slRef write - no other strategy-state mutation, no order/latch/session writes)
'@
$lines[53] = @'
D3 16:45 live-activation (LIVE rule, E-hunk code - council clears; run time spent): RUNTIME under the section-1 live ext1 adoption (ext1Defined and finite slExt1 and SlimbProtectiveSideOk with domain conjunct, per L7/L9): the live stop on the 09-08 16:40 bar is 1.16359 (slot 91); the superseded live stop was 1.16274, giving slDist 146 pts against tpDist 99 pts for R 0.68 below the 1.0 gate - no fire, no SIGNAL 16:45:01, no A3 trade, no A3 EXITVERDICT/MTEXIT/MTLIFE rows. Runtime proof lands on the v36 segment (SLEXT481 S5 seq-13 row plus STOPRESOLVE probe_sel=2 row with slLive==pxExt1 plus SIDE1X liveStop 1.16359 plus TP_ELECT R 0.68 non-fire plus zero SIGNAL 16:45:01 two-pattern). Acceptance G3: the run proves on cited section-2 rows that the live rule kills A3 at runtime and no other listed row changes fire status (runtime grades, never counterfactual; flips means fire-status only: A1 R 1.48 to 1.38 with status unchanged; only A3 status flips). Guard evaluation carried from v35 (146 pts A3 / 78 pts A1) plus domain conjunct text-checked at build.
'@
foreach ($i in @(0,2,4,6,8,47,53)) { Assert-Ascii $lines[$i] "full-L$($i+1)" }
"FULL_OK=7"
# ---- substring replaces (16 lines) ----
Rep1 10 'liveSel=-1 is directly caused by both selector predicates failing.' 'liveSel=-1 is directly caused by both selector predicates failing. On the v36 ext1 arm the selector is bypassed (s1x_sel=2, L9); this paragraph governs the else-arm fallback only.' 'L11-arm'
Rep1 12 'A3 (09-08 16:40-bar fire, declined), A1 (08-28 16:20-bar fire' 'A3 (09-08 16:40-bar fire) decline SUPERSEDED by the v36 live kill (no signal to decline; kill-all decline recorded as history), A1 (08-28 16:20-bar fire' 'L13-A3'
Rep1 14 'PREDICTED under the future rule' 'LIVE under the v36 rule' 'L15a'
Rep1 14 'not graded this run' 'graded at runtime this run' 'L15b'
Rep1 14 'the print-only run itself keeps 7 TP_ELECT fire rows of 11 TP_ELECT rows total per section 4;' 'the live run prints 6 TP_ELECT fire rows of 11 TP_ELECT rows total per section 4 (A3 non-fire at runtime);' 'L15c'
Rep1 19 '| 08-28 16:20 SHORT (A1 declined) | 1.16430 / 1.16322 | 1.16508 | 1.38, passes R-gate; decline unchanged; no outcome delta;' '| 08-28 16:20 SHORT (A1 declined) | 1.16430 / 1.16322 | 1.16508 | 1.38 at runtime, passes R-gate; decline unchanged;' 'L20-A1'
Rep1 24 '| 09-08 16:40 SHORT (A3 declined) | 1.16213 / 1.16114 | 1.16359 | 0.68 shadow R-gate kill, no fire;' '| 09-08 16:40 SHORT (A3 declined) | 1.16213 / 1.16114 | 1.16359 | 0.68 live R-gate kill at runtime, no fire, no SIGNAL;' 'L25-A3'
Rep1 27 'are counterfactual (print-only).' 'run live on the S5 path this run.' 'L28a'
Rep1 27 'PREDICTED source-changed bars under this rule:' 'LIVE source-changed bars under this rule:' 'L28b'
Rep1 27 'Five other fires PREDICTED identical because live stop already equals s1px there (prediction only, resolved by prints' 'Five other fires print identical because live stop already equals s1px there (resolved by prints' 'L28c1'
Rep1 27 'never a pre-accepted result).' 'never pre-accepted).' 'L28c2'
Rep1 27 '(b) stop-value difference from parsed binary64 probe price values' '(b) stop-value difference from parsed binary64 probe price values (liveSel=2 arm: slLive==pxExt1 mandatory)' 'L28d'
Rep1 27 'A3 live stop 1.16274' 'A3 live stop 1.16359 (superseding the archived 1.16274)' 'L28e1'
Rep1 27 'and actual R 1.62' 'with archived actual R 1.62 (superseded at runtime by 0.68)' 'L28e2'
Rep1 27 'vetoed before latch (no TP_ELECT row); current means silent, no signal/fire outcome' 'vetoed before latch (no TP_ELECT row; live ext1 adoption precedes the veto with refusal unchanged); current means silent, no signal/fire outcome' 'L28f'
Rep1 29 '## 3. Probe form (print-only = no strategy-state mutation, no NEW live selector/gate substitution (the S1-LIVE-STOPFIX-001 rewire is already live in 6C2E4028), no change to existing strategy control flow, no unload request' '## 3. Live form (E-hunk executes the section-1 rule with one declared slRef live write at the former selector site; A/B/C/D1/D2 carried print-only (the S1-LIVE-STOPFIX-001 rewire is already live in 6C2E4028), no other change to existing strategy control flow, no unload request' 'L30a'
Rep1 29 'THREE insertions A+B+C' 'THREE carried insertions A+B+C plus the new E-hunk' 'L30b'
Rep1 29 'section-1 rule NOT executed)' 'section-1 rule EXECUTED by the E-hunk)' 'L30c'
Rep1 33 'liveSel:INT:2:99-halts (99 forbidden; offline poison rule halts grading);' 'liveSel:INT:2:99-halts (99 forbidden; offline poison rule halts grading) plus 2-ext1-arm (slLive==pxExt1 mandatory, guard plus domain rechecked offline);' 'L34a'
Rep1 33 'No assignment to the live path.' 'No assignment to the live path except the L9 E-hunk slRef write under this authorization.' 'L34b1'
Rep1 33 'AdoptOff held, OrderSend 0.' 'AdoptOff held (dormant block inert, InpAdoptExt1=false), OrderSend 0 (measured this turn).' 'L34b2'
Rep1 33 'Live activation only via later dual-key plus tokens.' 'Live activation executes under this authorization (E-hunk); nothing further without token.' 'L34b3'
Rep1 35 'validity unprovable at this site) is invalid for this comparison and prints 0' 'validity unprovable at this site) is invalid for this comparison and prints 0; liveSel=2 (ext1 arm) likewise prints 0 (selector-fired incumbent required; reported, never graded)' 'L36a'
Rep1 37 'exact-diff = insertions A+B+C literal source text, except the two explicitly named STAGE-1-bound RHS expressions,' 'exact-diff = insertions A+B+C literal source text (carried byte-identical, tags -v28) plus the L9 E-hunk (new, tag -v36), except the two explicitly named STAGE-1-bound RHS expressions,' 'L38a'
Rep1 37 'because the probe performs none);' 'because the carried probe performs none, with the SOLE exception of the L9 E-hunk slRef write declared and gated here);' 'L38b'
Rep1 39 'this probe output settles' 'this run settles at runtime' 'L40a'
Rep1 39 'runtime ordering of veto/latch/SIGNAL/session-mark is settled by the filed source mapping plus diagnostic contract, never by probe-output proximity;' 'runtime ordering of veto/latch/SIGNAL/session-mark is settled by the filed source mapping plus diagnostic contract, never by output proximity (A3 kill ordered resolution-then-veto, proven by the absent SIGNAL);' 'L40b'
Rep1 41 'Actual-path baseline: 7 TP_ELECT fire rows of 11 TP_ELECT rows total,' 'Actual-path baseline: 6 TP_ELECT fire rows of 11 TP_ELECT rows total (A3 prints R 0.68 non-fire),' 'L42a'
Rep1 41 '(A1 and A3 fire-but-declined among them; the print-only run itself keeps all 7 fire rows' '(A1 fire-but-declined among them; the live run prints 6 fire rows (A3 non-fire at runtime)' 'L42b'
Rep1 41 'the predicted post-activation count 6 from section 2 is the counterfactual (conditioned' 'the section-2 post-activation count 6 prints at runtime (conditioned' 'L42c'
Rep1 41 '7 TP_ELECT fire rows unchanged, A3 still present at actual-path R=1.62 per the archived A3 TP_ELECT row (comparison value with source record' '6 TP_ELECT fire rows; A3 TP_ELECT row prints R 0.68 non-fire with no SIGNAL 16:45:01 (runtime grades, archived 1.62 row superseded as the live value' 'L42d'
Rep1 41 'MANDATORY findings (never struck): the 7 TP_ELECT fire rows, the A1 record-at-C plus self-consistency,' 'MANDATORY findings (never struck): the 6 TP_ELECT fire rows plus the A3 0.68 non-fire row, the A1 record-at-C plus self-consistency,' 'L42e'
Rep1 45 'Opus-v179 B-7 CARRIED for the live-activation relay opening line (named here, out of this probe envelope)' 'Opus-v179 B-7 ADOPTED as the L9 E-hunk (this relay)' 'L46a1'
Rep1 45 'existing L9661-L9665 selector unchanged in effect.' 'existing L9661-L9665 selector effect-identical in the else arm under the L9 E-hunk (Opus-v179 B-7 adopted here).' 'L46a2'
# L46c DROPPED 2026-09-20: anchor 'probe-vs-helper ... opening open-item' occurs 0x in the packet (verdict-only text, GLM-V198 Ask B (d), never folded) - fulfillment rides the L7/L9 E-hunk plus the L46b append, never a phantom amend.
Rep1 45 'this probe settles' 'this run proves at runtime; the carried probe joins still settle' 'L46d'
Rep1 45 'items 5-6 carried for the live relay (side-guard hazard plus direction precondition under the P007 FLAG context)' 'items 5-6 adopted in v36 (guard inline; domain conjunct)' 'L46e'
Rep1 45 'items 3/6 answered-or-carried (discovery boundary recorded; side-guard stays live-relay)' 'items 3/6 answered-or-adopted (discovery boundary recorded; side-guard adopted in v36)' 'L46f'
Rep1 45 'No new verdicts this round; Opus still out. Council may amend-with-delta on any line; builder invents nothing.' 'No new verdicts this round; Opus still out. Luna-V198-1-7: 1 adopted (P050 post-floor wording, L50), 2-4 recorded (run-scoped volStep premise; disclosed G2 non-exhaustiveness; G4 completeness boundary), 5-6 closed by the E-hunk (DIR_NONE domain conjunct; s1x_sel=2 metadata); Luna Ask B: 1 declined (L10105 capture re-opens D1 for zero gain), 2 carried to the seed-mechanism packet (STATE branch), 3 adopted (this E-hunk), 4 carried (L11169 layer, no new code). Sonnet-V198: close, nothing open. GLM-V198-1-5 adopted (L1 banner precision; L56 parenthetical; L56 exit-bar check; L58 question citation; L56 flag context); GLM Ask B: a-c adopted as v36 one-liners plus exit-bar check, d adopted (this relay with P046 guard inline plus DIR_NONE plus probe-vs-helper moot note), e declined standing (trade-id field, LOTDIAG tick stamp). Council may amend-with-delta on any line; builder invents nothing.' 'L46b'
Rep1 49 'computed from the in-memory unformatted lots value (the L10110 operand; not a pre-floor predicate)' 'computed from the post-MathFloor, unformatted lots value (the L10110 operand; not a pre-floor predicate)' 'L50a'
Rep1 49 'Acceptance G1: the 09-04 15:55-bar evaluation (16:00:00 tick) and the 08-28 16:20-bar evaluation (16:25:00 tick) each print LOTDIAG with belowMin=1 (exact witness,' 'Acceptance G1 (USD envelope): every lot-calc bar prints LOTDIAG with belowMin=0 (no floor-refusal expected at Deposit 10000 USD; any belowMin=1 halts with operands); the 09-04 15:55-bar evaluation (16:00:00 tick) and the 08-28 16:20-bar evaluation (16:25:00 tick) print LOTDIAG with belowMin=0 (exact witness,' 'L50b'
Rep1 49 'and flooredLots below volMin at printed resolution immediately before the same-tick ABORT/A6REFUSED pair;' 'with flooredLots at or above volMin and no ABORT/A6REFUSED lot pair on any bar;' 'L50c'
Rep1 49 'takes join 4/4 at signal level over the membership 8/28 10:00 SHORT Daily-VWAP plus 9/4 15:55 LONG plus 9/7 09:15 LONG plus 9/7 16:40 LONG matched to his TAKEN rows 8/28 plus-0.10, 9/4 plus-0.84, 9/7 plus-2.03, 9/7 plus-1.06 by evaluated-bar timestamp plus direction' 'takes join 4/4 at deal level over the membership 8/28 10:00 SHORT Daily-VWAP plus 9/4 15:55 LONG plus 9/7 09:15 LONG plus 9/7 16:40 LONG matched to his TAKEN rows 8/28 plus-0.10, 9/4 plus-0.84, 9/7 plus-2.03, 9/7 plus-1.06 by evaluated-bar timestamp plus direction with PRE-SEND lots plus deal present (9/4 executes at USD scale)' 'L50d'
Rep1 55 '(8 rows, 10:20 through 10:40 ride the re-proven disk census)' '(8 rows curTp 1.16364 at 10:05-10:40, all 9 pasted whole v198)' 'L56a'
Rep1 55 '(exit-bar curTp equals MTEXIT exit on both filed instances: T1 1.16459, T2 1.16416)' '(exit-bar curTp equals MTEXIT exit on both filed instances: T1 1.16459, T2 1.16416 - explicit Stage-1/Stage-3 check this run: T1 10:45 curTp == MTEXIT exit 1.16459; T2 16:25 curTp == MTEXIT exit 1.16416)' 'L56b'
Rep1 55 '(T1 envelope [1.16322, 1.16459]; T2 envelope [1.16322, 1.16416]) (lifecycle-completeness: entry TP at selection vs per-bar curTp at manage).' '(T1 envelope [1.16322, 1.16459]; T2 envelope [1.16322, 1.16416]) (want/anti/htf* ride as ungraded context, never a grading rule) (lifecycle-completeness: entry TP at selection vs per-bar curTp at manage).' 'L56c'
Rep1 57 'STAGE-1: EA pre-hash 9C79FC1E plus 613044 B re-measured at build with halt on drift;' 'STAGE-1: EA pre-hash 7C247F459A983F6BD3D234D84DE366C6F3F9B78DC6CDDDB3A0415AA4D295E8A3 plus 614043 B re-measured at build with halt on drift;' 'L58a'
Rep1 57 'exact-diff gate checks the build tree against the four v32 literals above (D1 pure insertion in v32 wording, D2a/D2b wraps with old-to-new pairs, D2c pure insertion) with tag -v32 naming the set (D1 in v32 wording; D2a/D2b/D2c unchanged);' 'exact-diff gate checks the build tree against the four v32 literals above (D1 pure insertion in v32 wording, D2a/D2b wraps with old-to-new pairs, D2c pure insertion) with tag -v32 naming the carried set (D1 in v32 wording; D2a/D2b/D2c unchanged) PLUS the L9 E-hunk (new, tag -v36: old-verbatim current L9663-L9667 to new-verbatim; fallback five statements effect-identical modulo indent; domain conjunct plus guard call plus s1x_sel=2 text-checked; B L9668 unchanged);' 'L58b'
Rep1 57 'run range frozen from terminal.ini [Tester] (same window 08-26 to 09-09, same envelope RECON44_DEMO_P1, InpMode 1, InpDebugLog=true - SEEDDIAG is gated on it, so a run with it false fails G2 by missing lines);' 'run range frozen from terminal.ini [Tester] (same window 08-26 to 09-09, new envelope RECON50_DEMO_USD (RECON44_DEMO_P1 bytes with Currency JPY to USD; Deposit 10000; same Symbol/Period/Model/Leverage/inputs; STAGE-1 byte-asserts the single-line delta), InpMode 1, InpDebugLog=true - SEEDDIAG is gated on it, so a run with it false fails G2 by missing lines);' 'L58c'
Rep1 57 'Novel evidence this run returns that no prior run did: (a) LOTDIAG lines with belowMin=1 plus the rawLots rounded context on the two floor-refused bars (v30 segments prove the aborts, never the computed lots - PRE-SEND prints lots on takes only); (b) SEEDDIAG 17:00 branch name on 9/8 17:00 (v30 proves proximate death S2POLL IDLE/NODIR plus CQD EMPTY plus zero S5 evals, never which S1 branch refused); (c) EXITVERDICT curTp column joined bar-for-bar to his +0.10 row (no filed artifact performs the join). D3 spends no run time (carried v30 proof).' 'Novel evidence this run returns that no prior run did: (a) E-hunk live kill of A3 at runtime (no SIGNAL 16:45:01 two-pattern; TP_ELECT R 0.68 non-fire; SIDE1X liveStop 1.16359; probe_sel=2 row with slLive==pxExt1 - v35 proved the counterfactual only); (b) USD deal-level takes 4/4 with the 9/4 15:55 take executing (no prior run took above the floor); (c) lot-independent signal-path no-drift vs RECON49 (all SIGNAL plus TP_ELECT rows except A1/A3 reproduce - selection/gate rows never consume lots); (d) exit-bar equality as an explicit check (T1/T2). D3 RUNS live at runtime (E-hunk adoption); the v35 counterfactual is retired, never re-graded.' 'L58d'
Rep1 57 'Takes join 4/4 at signal level moves recall at entry; G2 names the 17:00 miss mechanism; G4 opens the exit model - each moves a named goal metric.' 'Takes join 4/4 at deal level moves takes; the A3 kill moves precision; G2 names the 17:00 miss mechanism; G4 opens the exit model - each moves a named goal metric.' 'L58e'
Rep1 57 'run-to-packet attribution by content plus post-insertion hash (new families carry no pkt tag; STOPRESOLVE wire stays -v28/6C2E4028).' 'run-to-packet attribution by content plus post-insertion hash (new families carry no pkt tag; STOPRESOLVE wire stays -v28/6C2E4028). Adherence (read-only, 7C247F45 base): R-gate holds (L57 default 1.0; L9673 compound predicate); alert-only holds (OrderSend count 0 this turn); setup-independence plus divergence-latch carried plus diff-confinement (E-hunk touches neither region); side-owner violation carried (L7708 POI-retest owned, L7519 second writer; out of v36 scope); stop-selection replaced at S5 by the E-hunk (rule-7 replace direction); imbalance-conditional plus wick plus filed-authority stay open; A+ directional (one false alert removed, 8/28 news-bar alert plus unruled takes stay open). STAGE-1 re-confirms digest plus confinement post-build, else halt.' 'L58f'
# ---- E-hunk disk asserts ----
$ea = [IO.File]::ReadAllLines($EA)
$old5 = @('         int s1x_sel = -1;', '         if(s1x_s0slot >= 0 && s1x_s0imb > 0) s1x_sel = 0;', '         else if(s1x_s1slot >= 0) s1x_sel = 1;', '         if(s1x_sel == 0) slRef = s1x_s0px;', '         else if(s1x_sel == 1) slRef = s1x_s1px;')
for ($k = 0; $k -lt 5; $k++) { if ($ea[9662 + $k] -ne $old5[$k]) { throw "EA L$((9663+$k)) mismatch" } }
"EA_OLDVERBATIM_OK=5"
foreach ($q in @('s1x_sel = 2', 'slRef = g_sl41_px', 'SlimbProtectiveSideOk(g_dir, g_sl41_px, currentPrice)', '(g_dir == DIR_LONG || g_dir == DIR_SHORT)')) {
  if ((Count-Hits $lines[8] $q) -ne 1) { throw "E-hunk quote $q" }
}
"EA_NEWVERBATIM_OK=4"
# ---- twin / identical verify ----
$ident = @(16,18,20,21,22,23,25,31,43,51) + @(1,3,5,7,9,11,13,15,17,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56)
foreach ($i in $ident) { if ($lines[$i] -ne $pre[$i]) { throw "twin-drift idx $i" } }
"TWIN_IDENTICAL=35"
$amended = @(0,2,4,6,8,10,12,14,19,24,27,29,33,35,37,39,41,45,47,49,53,55,57)
"TWIN_AMENDED=23"
# ---- ellipsis / census / sweeps ----
$all = $lines -join "`n"
$ell = ([regex]::Matches($all, '\.\.\.')).Count
"ELLIPSIS=$ell"
if ($ell -ne 0) { throw 'ellipsis' }
"---DIGEST-CENSUS---"
[regex]::Matches($all, '[0-9A-F]{8,}') | Group-Object Value | Sort-Object Name | ForEach-Object { "$($_.Count)x $($_.Name)" }
"---LEFTOVER-SWEEP---"
foreach ($pat in @('FUTURE', 'counterfactual', 'print-only', 'same envelope', 'RECON44_DEMO_P1', 'JPY', 'D3 spends no run time', 'never live activation', 'no NEW live selector', 'Live activation only via later', '7 TP_ELECT fire rows', '9C79FC1E', 'InpAdoptExt1=false', 'v35', 'counterfactual (never a')) {
  $hits = @()
  for ($i = 0; $i -lt 58; $i++) { if ($lines[$i].Contains($pat)) { $hits += "L$($i+1)" } }
  "$pat => $($hits -join ',')"
}
# ---- write ----
$enc = New-Object Text.UTF8Encoding($hasBom)
[IO.File]::WriteAllText($Pkt, (($lines -join "`n") + "`n"), $enc)
$post = Get-FileHash -LiteralPath $Pkt -Algorithm SHA256
$bytes = (Get-Item -LiteralPath $Pkt).Length
"POST_HASH=$($post.Hash) POST_BYTES=$bytes POST_LINES=$(([IO.File]::ReadAllLines($Pkt)).Count)"
