$j='c:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\06_HANDOFFS\RECON17-SLDEF6_JOURNAL.log'
$out='c:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\06_HANDOFFS\RECON17-SLDEF6_TABULATION.txt'
function C($pat){ (Select-String -LiteralPath $j -Pattern $pat | Measure-Object).Count }
function L($pat){ ((Select-String -LiteralPath $j -Pattern $pat).Line -join '|') }
$r=@()
$r+=('G1 bars/ticks: '+(L 'bars generated'))
$r+=('SIGNAL_COUNT='+(C '\[SRJ-EA\] \d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2} SIGNAL '))
$r+=('SIGNALS='+(L '\[SRJ-EA\] \d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2} SIGNAL '))
$r+=('WS161='+(L 'WS161_CENSUS'))
$r+=('WS161_MISMATCH_ROWS='+(C 'WS161_MISMATCH(?!.*mismatch=0)'))
$r+=('SLIMB_TOTAL='+(C '\[SRJ-EA\] SLIMB fields=19'))
$r+=('WALK_OB_TOTAL='+(C '\[SRJ-EA\] SLIMBWALK fields=27'))
$r+=('WALKF_TOTAL='+(C '\[SRJ-EA\] SLIMBWALKF fields=25'))
$r+=('WALK_OB_SIDEV_GT0='+(C '\[SRJ-EA\] SLIMBWALK fields=27.*sideViolations=[1-9]'))
$r+=('WALKF_SIDEV_GT0='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*sideFracViolations=[1-9]'))
$r+=('SLIMBR_TOTAL='+(C '\[SRJ-EA\] SLIMBR bar='))
$r+=('SLIMBR_STALE='+(C '\[SRJ-EA\] SLIMBR bar=.*STALE'))
$r+=('SLADDER_TOTAL='+(C '\[SRJ-EA\] SLADDER fields=19'))
$r+=('SLADDER_BADFMT='+(C '\[SRJ-EA\] SLADDER (?!fields=19)'))
$r+=('SLADDER_BARS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER fields=19 bar=(\S+ \S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+':'+$_.Count }) -join ' '))
$r+=('SLADCORR_TOTAL='+(C '\[SRJ-EA\] SLADCORR fields=23'))
$r+=('SLADCORR_COVERS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADCORR fields=23.*ladCovers=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADCORR_FINAL='+(L '\[SRJ-EA\] SLADCORR_FINAL'))
$r+=('SIGMAP='+(L '\[SRJ-EA\] SIGMAP'))
$r+=('SLADDERMATCH_STATUS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_MATCH fields=14.*status=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADDERMATCH_TODAYREF='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_MATCH fields=14.*todayRef=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_TOTAL='+(C '\[SRJ-EA\] SLADWIN fields=28'))
$r+=('SLADWIN_BADFMT='+(C '\[SRJ-EA\] SLADWIN (?!fields=28)'))
$r+=('SLADWIN_STATUS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=28.*status=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_COVERS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=28.*ladCovers=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_OBLIGN='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=28.*ladObligN=(\d+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_ROWS='+(L '\[SRJ-EA\] SLADWIN fields=28'))
$r+=('REF_OB_DEEP_TOTAL='+(C '\[SRJ-EA\] REF_OB_DEEP fields=10'))
$r+=('ORDER_OUTCOMES='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*gateOutcome=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('ORDER_STAMP='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*seqStamp=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT1_TOTAL='+(C '\[SRJ-EA\] SLEXT1 fields=29'))
$r+=('SLEXT1_VERDICTS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT1 fields=29.*verdict=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT1_TODAYXI='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT1 fields=29.*todayXi=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT1_AUG28='+(L '\[SRJ-EA\] SLEXT1 fields=29 bar=2026\.08\.28 10:00'))
$r+=('SLEXT6HALT_TOTAL='+(C '\[SRJ-EA\] SLEXT6HALT'))
$r+=('SLNONFIRE_WOULDFIRE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLNONFIRE fields=11.*wouldFire=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXTLOST_TOTAL='+(C '\[SRJ-EA\] SLEXTLOST'))
$r+=('SLEXT_FINAL='+(L '\[SRJ-EA\] SLEXT_FINAL'))
$r+=('SLADMARK_TOTAL='+(C '\[SRJ-EA\] SLADMARK fields=11'))
$r+=('SLADMARK_BARS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADMARK fields=11 bar=(\S+ \S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+':'+$_.Count }) -join ' '))
$r+=('DECISION_HDR='+(L '\[SRJ-EA\] SLADDER_DECISION rows='))
$r+=('DECISION_ROW_N='+(C '\[SRJ-EA\] SLADDER_DECISION_ROW fields=14'))
$r+=('DECISION_FIRED='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_DECISION_ROW fields=14.*fired=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('MTEXIT_N='+(C '\[SRJ-EA\] MTEXIT bar='))
$r+=('MTLIFE_N='+(C '\[SRJ-EA\] MTLIFE fields=11'))
$r+=('MTFLIP_N='+(C '\[SRJ-EA\] MTFLIP fields=10'))
$r+=('N1EQUALS='+(L '\[SRJ-EA\] N1EQUALS'))
$r+=('FRAME_NOTE='+(L '\[SRJ-EA\] FRAME_NOTE offset='))
$r+=('TABLE_NOTE='+(L '\[SRJ-EA\] TABLE_NOTE'))
$r+=('BLACKOUT_CENSUS='+(L '\[SRJ-EA\] BLACKOUT_CENSUS'))
$r+=('LINEWIDTH_TRUNC_NZ='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] LINEWIDTH class="[^"]+" max=\d+ cap=\d+ truncated=([1-9]\d*)').Count)))
$r+=('LINEWIDTH_SLADWIN28='+(L 'LINEWIDTH class="SLADWIN"'))
$r+=('LINEWIDTH_SLEXT481='+(L 'LINEWIDTH class="SLEXT481"'))
$r+=('LINEWIDTH_SLEXT43='+(L 'LINEWIDTH class="SLEXT43"'))
$r+=('LINEWIDTH_SLEXT45='+(L 'LINEWIDTH class="SLEXT45"'))
$r+=('DECISION_ROWS='+(C 'SLIMBR_DECISION rows='))
$r+=('SPOT_INPLAY_N='+(C 'INPLAYCOMMIT.*applied=1'))
$r+=('SLEXT481_TOTAL='+(C '\[SRJ-EA\] SLEXT481 fields=17'))
$r+=('SLEXT481_SITE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT481 fields=17.*site=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT481_NOORIGIN='+(C '\[SRJ-EA\] SLEXT481 fields=17.*ladOriginPx=-'))
$r+=('SLEXT481_UNDEF='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT481 fields=17.*ext1Defined=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT41HALT_TOTAL='+(C '\[SRJ-EA\] SLEXT41HALT'))
$r+=('SLEXT481_SEP8='+(L '\[SRJ-EA\] SLEXT481 fields=17.*sep8Covered=1'))
$r+=('SLEXT43_TOTAL='+(C '\[SRJ-EA\] SLEXT43 fields=10'))
$r+=('SLEXT43_ROWS='+(L '\[SRJ-EA\] SLEXT43 fields=10'))
$r+=('SLEXT43_FINAL='+(L '\[SRJ-EA\] SLEXT43_FINAL'))
$r+=('SLEXT45_TOTAL='+(C '\[SRJ-EA\] SLEXT45 fields=10'))
$r+=('SLEXT45_TODAY='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT45 fields=10.*todayStatus=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT45_EXT='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT45 fields=10.*extStatus=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT45_COVER='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT45 fields=10.*coverStatus=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT45_ROWS='+(L '\[SRJ-EA\] SLEXT45 fields=10'))
$r+=('SLIMBCARVE_PROXY='+(L '\[SRJ-EA\] SLIMBCARVE_PROXY'))
$r+=('SLMEMO_CENSUS='+(L '\[SRJ-EA\] SLMEMO_CENSUS'))
$r | Set-Content -LiteralPath $out
Get-Content -LiteralPath $out
