$j='c:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\06_HANDOFFS\RECON19-ORIGIN1_JOURNAL.log'
$out='c:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\06_HANDOFFS\RECON19-ORIGIN1_TABULATION.txt'
function C($pat){ (Select-String -LiteralPath $j -Pattern $pat | Measure-Object).Count }
function L($pat){ ((Select-String -LiteralPath $j -Pattern $pat).Line -join '|') }
$r=@()
$r+=('G1 bars/ticks: '+(L 'bars generated'))
$r+=('SIGNAL_COUNT='+(C '\[SRJ-EA\] \d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2} SIGNAL '))
$r+=('WS161='+(L 'WS161_CENSUS'))
$r+=('SLIMB_TOTAL='+(C '\[SRJ-EA\] SLIMB fields=19'))
$r+=('WALK_OB_TOTAL='+(C '\[SRJ-EA\] SLIMBWALK fields=27'))
$r+=('WALKF_TOTAL='+(C '\[SRJ-EA\] SLIMBWALKF fields=25'))
$r+=('WALK_OB_SIDEV_GT0='+(C '\[SRJ-EA\] SLIMBWALK fields=27.*sideViolations=[1-9]'))
$r+=('WALKF_SIDEV_GT0='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*sideFracViolations=[1-9]'))
$r+=('SLIMBR_TOTAL='+(C '\[SRJ-EA\] SLIMBR bar='))
$r+=('SLIMBR_STALE='+(C '\[SRJ-EA\] SLIMBR bar=.*STALE'))
$r+=('SIGMAP='+(L '\[SRJ-EA\] SIGMAP'))
$r+=('SLADDERMATCH_STATUS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_MATCH fields=14.*status=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('ORDER_OUTCOMES='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*gateOutcome=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT1_VERDICTS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT1 fields=29.*verdict=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT6HALT_TOTAL='+(C '\[SRJ-EA\] SLEXT6HALT'))
$r+=('SLEXT_FINAL='+(L '\[SRJ-EA\] SLEXT_FINAL'))
$r+=('DECISION_HDR='+(L '\[SRJ-EA\] SLADDER_DECISION rows='))
$r+=('MTEXIT_N='+(C '\[SRJ-EA\] MTEXIT bar='))
$r+=('MTLIFE_N='+(C '\[SRJ-EA\] MTLIFE fields=11'))
$r+=('MTFLIP_N='+(C '\[SRJ-EA\] MTFLIP fields=10'))
$r+=('N1EQUALS='+(L '\[SRJ-EA\] N1EQUALS'))
$r+=('FRAME_NOTE='+(L '\[SRJ-EA\] FRAME_NOTE offset='))
$r+=('LINEWIDTH_TRUNC_NZ='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] LINEWIDTH class="[^"]+" max=\d+ cap=\d+ truncated=([1-9]\d*)').Count)))
$r+=('LINEWIDTH_ORIGINREG='+(L 'LINEWIDTH class="ORIGINREG"'))
$r+=('LINEWIDTH_ORIGINCAND='+(L 'LINEWIDTH class="ORIGINCAND"'))
$r+=('LINEWIDTH_SLORIGPV='+(L 'LINEWIDTH class="SLORIGPV"'))
$r+=('SPOT_INPLAY_N='+(C 'INPLAYCOMMIT.*applied=1'))
$r+=('SLEXT481_TOTAL='+(C '\[SRJ-EA\] SLEXT481 fields=17'))
$r+=('SLEXT481_SITE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT481 fields=17.*site=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT41HALT_TOTAL='+(C '\[SRJ-EA\] SLEXT41HALT'))
$r+=('SLEXT43_FINAL='+(L '\[SRJ-EA\] SLEXT43_FINAL'))
$r+=('SLEXT45_TODAY='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT45 fields=10.*todayStatus=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLIMBCARVE_PROXY='+(L '\[SRJ-EA\] SLIMBCARVE_PROXY'))
$r+=('SLMEMO_CENSUS='+(L '\[SRJ-EA\] SLMEMO_CENSUS'))
$r+=('SLSEP846_FINAL='+(L '\[SRJ-EA\] SLSEP846_FINAL'))
$r+=('SLEXT47_FINAL='+(L '\[SRJ-EA\] SLEXT47_FINAL'))
$r+=('SLORIG48_FINAL='+(L '\[SRJ-EA\] SLORIG48_FINAL'))
$r+=('ORIGIN_MANIFEST_N='+(C '\[SRJ-EA\] ORIGIN_MANIFEST fields=6'))
$r+=('ORIGIN_MANIFEST='+(L '\[SRJ-EA\] ORIGIN_MANIFEST fields=6'))
$r+=('ORIGINREG_TOTAL='+(C '\[SRJ-EA\] ORIGINREG fields=23'))
$r+=('ORIGINREG_ROWS='+(L '\[SRJ-EA\] ORIGINREG fields=23'))
$r+=('ORIGINREGFAIL_TOTAL='+(C '\[SRJ-EA\] ORIGINREGFAIL'))
$r+=('ORIGINREG_FINAL='+(L '\[SRJ-EA\] ORIGINREG_FINAL'))
$r+=('ORIGINCAND_TOTAL='+(C '\[SRJ-EA\] ORIGINCAND fields=19'))
$r+=('ORIGINCAND_ROWS='+(L '\[SRJ-EA\] ORIGINCAND fields=19'))
$r+=('ORIGINCAND_SKIPPED='+(L '\[SRJ-EA\] ORIGINCAND_SKIPPED'))
$r+=('ORIGINCAND_FINAL='+(L '\[SRJ-EA\] ORIGINCAND_FINAL'))
$r+=('SLORIGPV_TOTAL='+(C '\[SRJ-EA\] SLORIGPV fields=11'))
$r+=('SLORIGPV_AGREE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLORIGPV fields=11.*agree=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('ORIGINPROV_FINAL='+(L '\[SRJ-EA\] ORIGINPROV_FINAL'))
$r+=('SUPPRESSED_TOTAL='+(C '\[SRJ-EA\] SUPPRESSED'))
$r | Set-Content -LiteralPath $out
Get-Content -LiteralPath $out
