$j='c:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\06_HANDOFFS\RECON16-SLDEF5_JOURNAL.log'
$out='c:\Users\winar\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06\MQL5\SRJ_FlowNexus_Local\06_HANDOFFS\RECON16-SLDEF5_TABULATION.txt'
function C($pat){ (Select-String -LiteralPath $j -Pattern $pat | Measure-Object).Count }
function L($pat){ ((Select-String -LiteralPath $j -Pattern $pat).Line -join '|') }
$r=@()
$r+=('G1 bars/ticks: '+(L 'bars generated'))
$r+=('SIGNAL_COUNT='+(C '\[SRJ-EA\] \d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2} SIGNAL '))
$r+=('SIGNALS='+(L '\[SRJ-EA\] \d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2} SIGNAL '))
$r+=('WS161='+(L 'WS161_CENSUS'))
$r+=('WS161_MISMATCH_ROWS='+(C 'WS161_MISMATCH(?!.*mismatch=0)'))
$r+=('ABORTS: FRESH_OB_DEAD='+(C 'reason=FRESH_OB_DEAD')+' LTF_MISALIGN='+(C 'reason=LTF_MISALIGN')+' SESSION_CLOSED='+(C 'reason=SESSION_CLOSED')+' TP_RR_FAIL='+(C 'reason=TP_RR_FAIL')+' NO_TP_TARGET='+(C 'reason=NO_TP_TARGET')+' NO_SL_REF='+(C 'reason=NO_SL_REF')+' FRESH_OPP_FVG='+(C 'reason=FRESH_OPP_FVG'))
$r+=('CQD_DIV_FIRST: total='+(C 'CQD DIV verdict=')+' +1='+(C 'CQD DIV verdict=\+1')+' +2='+(C 'CQD DIV verdict=\+2')+' -1='+(C 'CQD DIV verdict=-1')+' -2='+(C 'CQD DIV verdict=-2'))
$r+=('CONFIRMPOLL='+(C 'CONFIRMPOLL'))
$r+=('SUPPRESSED total='+(C 'SUPPRESSED'))
$r+=('PROMO_SCOPED='+(C 'XOB-PROMOCENSUS'))
$r+=('SLMEMO_CENSUS='+(L 'SLMEMO_CENSUS'))
$r+=('SL_REF_S2POLL='+(C 'SL_REF.*site=S2POLL')+' SL_REF_S3ARM='+(C 'SL_REF.*site=S3ARM')+' SL_REF_S5='+(C 'SL_REF.*site=S5'))
$r+=('INPLAYCOMMIT_APPLIED1='+(C 'INPLAYCOMMIT.*applied=1')+' COMMITTED1='+(C 'INPLAYCOMMIT.*applied=1.*committed=1'))
$r+=('MTEXIT_N='+(C '\[SRJ-EA\] MTEXIT bar='))
$r+=('MTEXIT='+(L '\[SRJ-EA\] MTEXIT bar='))
$r+=('MTEXIT_REASONS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] MTEXIT bar=\S+ \S+ reason=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('MTLIFE_N='+(C '\[SRJ-EA\] MTLIFE fields=11'))
$r+=('MTLIFE_BADFMT='+(C '\[SRJ-EA\] MTLIFE (?!fields=11)'))
$r+=('MTLIFE='+(L '\[SRJ-EA\] MTLIFE fields=11'))
$r+=('MTFLIP_N='+(C '\[SRJ-EA\] MTFLIP fields=10'))
$r+=('MTFLIP_BADFMT='+(C '\[SRJ-EA\] MTFLIP (?!fields=10)'))
$r+=('MTFLIP='+(L '\[SRJ-EA\] MTFLIP fields=10'))
$r+=('SLIMB_TOTAL='+(C '\[SRJ-EA\] SLIMB fields=19'))
$r+=('SLIMB_BADFMT='+(C '\[SRJ-EA\] SLIMB (?!fields=19)'))
$r+=('WALK_OB_TOTAL='+(C '\[SRJ-EA\] SLIMBWALK fields=27'))
$r+=('WALK_OB_BADFMT='+(C '\[SRJ-EA\] SLIMBWALK (?!fields=27)'))
$r+=('WALKF_TOTAL='+(C '\[SRJ-EA\] SLIMBWALKF fields=25'))
$r+=('WALKF_BADFMT='+(C '\[SRJ-EA\] SLIMBWALKF fields=25'))
$r+=('WALK_OB_SIDEV_GT0='+(C '\[SRJ-EA\] SLIMBWALK fields=27.*sideViolations=[1-9]'))
$r+=('WALKF_SIDEV_GT0='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*sideFracViolations=[1-9]'))
$r+=('WALKF_GUARD_APPLIED='+(C 'fracAnchorGuardApplied=1'))
$r+=('WALKF_ANCHORF1='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*fracAnchorFlag=1'))
$r+=('WALK_OB_CLASS_ALL3='+(C '\[SRJ-EA\] SLIMBWALK fields=27.* class=ALL3_EQ')+' UNRES='+(C '\[SRJ-EA\] SLIMBWALK fields=27.* class=UNRESOLVED')+' UNCLASS='+(C '\[SRJ-EA\] SLIMBWALK fields=27.* class=UNCLASSIFIED'))
$r+=('WALKF_CLASS_CARVE='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*fracClass=CARVEOUT_FIRED')+' UNRES='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*fracClass=UNRESOLVED')+' UNCLASS='+(C '\[SRJ-EA\] SLIMBWALKF fields=25.*fracClass=UNCLASSIFIED'))
$r+=('SLIMBR_TOTAL='+(C '\[SRJ-EA\] SLIMBR bar='))
$r+=('SLIMBR_STALE='+(C '\[SRJ-EA\] SLIMBR bar=.*STALE'))
$r+=('SLIMBR_EXT1='+(C '\[SRJ-EA\] SLIMBR bar=.*slExt1='))
$r+=('SLIMBR_OBCARVE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLIMBR bar=.*obCarveFired=(-?\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLIMBR_FRCARVE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLIMBR bar=.*frCarveFired=(-?\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADDER_TOTAL='+(C '\[SRJ-EA\] SLADDER fields=19'))
$r+=('SLADDER_BADFMT='+(C '\[SRJ-EA\] SLADDER (?!fields=19)'))
$r+=('SLADDER_STALEFRESH0='+(C '\[SRJ-EA\] SLADDER fields=19.*ladFresh=0'))
$r+=('SLADDER_BARS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER fields=19 bar=(\S+ \S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+':'+$_.Count }) -join ' '))
$r+=('SLADCORR_TOTAL='+(C '\[SRJ-EA\] SLADCORR fields=23'))
$r+=('SLADCORR_BADFMT='+(C '\[SRJ-EA\] SLADCORR (?!fields=23)'))
$r+=('SLADCORR_COVERS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADCORR fields=23.*ladCovers=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADCORR_CAPHIT='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADCORR fields=23.*ladCapHit=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADCORR_FRACOFF='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADCORR fields=23.*fracOffN=(\d+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADCORR_TODAYOFF='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADCORR fields=23.*todayOffN=(\d+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADCORR_ROWS='+(L '\[SRJ-EA\] SLADCORR fields=23'))
$r+=('SLADCORR_HIST='+(L '\[SRJ-EA\] SLADCORR_HIST'))
$r+=('SLADCORR_FINAL='+(L '\[SRJ-EA\] SLADCORR_FINAL'))
$r+=('SIGMAP='+(L '\[SRJ-EA\] SIGMAP'))
$r+=('SLADDERMATCH_TOTAL='+(C '\[SRJ-EA\] SLADDER_MATCH fields=14'))
$r+=('SLADDERMATCH_BADFMT='+(C '\[SRJ-EA\] SLADDER_MATCH (?!fields=14)'))
$r+=('SLADDERMATCH_STATUS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_MATCH fields=14.*status=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADDERMATCH_TODAYREF='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_MATCH fields=14.*todayRef=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_TOTAL='+(C '\[SRJ-EA\] SLADWIN fields=27'))
$r+=('SLADWIN_BADFMT='+(C '\[SRJ-EA\] SLADWIN (?!fields=27)'))
$r+=('SLADWIN_STATUS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=27.*status=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_COVERS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=27.*ladCovers=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_LIMITHIT='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=27.*ladLimitHit=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLADWIN_HALTREFS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADWIN fields=27.*haltRef=(\S+) haltSlot=(-?\d+)') | ForEach-Object { $_.Matches[1].Value+':'+$_.Matches[2].Value }) -join '|'))
$r+=('SLADWIN_ROWS='+(L '\[SRJ-EA\] SLADWIN fields=27'))
$r+=('REF_OB_DEEP_TOTAL='+(C '\[SRJ-EA\] REF_OB_DEEP fields=10'))
$r+=('REF_OB_DEEP_BADFMT='+(C '\[SRJ-EA\] REF_OB_DEEP (?!fields=10)'))
$r+=('REF_OB_DEEP='+(L '\[SRJ-EA\] REF_OB_DEEP fields=10'))
$r+=('ORDER_TOTAL='+(C '\[SRJ-EA\] ORDER fields=10'))
$r+=('ORDER_BADFMT='+(C '\[SRJ-EA\] ORDER (?!fields=10)'))
$r+=('ORDER_OUTCOMES='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*gateOutcome=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('ORDER_FLIPNEW1='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*flipNewThisBar=1.*') | ForEach-Object { $_.Line }) -join '|'))
$r+=('ORDER_OPPOSED='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*biasOpposedAtGate=(-?\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('ORDER_STAMP='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] ORDER fields=10.*seqStamp=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('ORDER_ROWS='+(L '\[SRJ-EA\] ORDER fields=10'))
$r+=('SLEXT1_TOTAL='+(C '\[SRJ-EA\] SLEXT1 fields=29'))
$r+=('SLEXT1_BADFMT='+(C '\[SRJ-EA\] SLEXT1 (?!fields=29)'))
$r+=('SLEXT1_VERDICTS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT1 fields=29.*verdict=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT1_TODAYXI='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLEXT1 fields=29.*todayXi=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLEXT1_ROWS='+(L '\[SRJ-EA\] SLEXT1 fields=29'))
$r+=('SLEXT6HALT_TOTAL='+(C '\[SRJ-EA\] SLEXT6HALT'))
$r+=('SLEXT6HALT_ROWS='+(L '\[SRJ-EA\] SLEXT6HALT'))
$r+=('SLNONFIRE_TOTAL='+(C '\[SRJ-EA\] SLNONFIRE fields=11'))
$r+=('SLNONFIRE_BADFMT='+(C '\[SRJ-EA\] SLNONFIRE (?!fields=11)'))
$r+=('SLNONFIRE_WOULDFIRE='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLNONFIRE fields=11.*wouldFire=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('SLNONFIRE_ROWS='+(L '\[SRJ-EA\] SLNONFIRE fields=11'))
$r+=('SLEXTLOST_TOTAL='+(C '\[SRJ-EA\] SLEXTLOST'))
$r+=('SLEXTLOST_ROWS='+(L '\[SRJ-EA\] SLEXTLOST'))
$r+=('SLEXT_FINAL='+(L '\[SRJ-EA\] SLEXT_FINAL'))
$r+=('SLADMARK_TOTAL='+(C '\[SRJ-EA\] SLADMARK fields=11'))
$r+=('SLADMARK_BADFMT='+(C '\[SRJ-EA\] SLADMARK (?!fields=11)'))
$r+=('SLADMARK_BARS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADMARK fields=11 bar=(\S+ \S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+':'+$_.Count }) -join ' '))
$r+=('DECISION_HDR='+(L '\[SRJ-EA\] SLADDER_DECISION rows='))
$r+=('DECISION_ROW_N='+(C '\[SRJ-EA\] SLADDER_DECISION_ROW fields=14'))
$r+=('DECISION_ROW_BADFMT='+(C '\[SRJ-EA\] SLADDER_DECISION_ROW (?!fields=14)'))
$r+=('DECISION_RUNG_N='+(C '\[SRJ-EA\] SLADDER_DECISION_RUNG fields=13'))
$r+=('DECISION_RUNG_BADFMT='+(C '\[SRJ-EA\] SLADDER_DECISION_RUNG (?!fields=13)'))
$r+=('DECISION_RUNG_KINDS='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_DECISION_RUNG fields=13.*kind=(\S+)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('DECISION_FIRED='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] SLADDER_DECISION_ROW fields=14.*fired=(\d)') | ForEach-Object { $_.Matches[0].Groups[1].Value } | Group-Object | ForEach-Object { $_.Name+'='+$_.Count }) -join ' '))
$r+=('N1EQUALS='+(L '\[SRJ-EA\] N1EQUALS'))
$r+=('N1PAIR='+(L '\[SRJ-EA\] N1PAIR'))
$r+=('FRAME_NOTE='+(L '\[SRJ-EA\] FRAME_NOTE offset='))
$r+=('TABLE_NOTE='+(L '\[SRJ-EA\] TABLE_NOTE'))
$r+=('BLACKOUT_ROW_N='+(C '\[SRJ-EA\] BLACKOUT_ROW'))
$r+=('BLACKOUT_BAR_N='+(C '\[SRJ-EA\] BLACKOUT_BAR'))
$r+=('BLACKOUT_HALT_N='+(C '\[SRJ-EA\] BLACKOUT_HALT_ROW'))
$r+=('BLACKOUT_CENSUS='+(L '\[SRJ-EA\] BLACKOUT_CENSUS'))
$r+=('LINEWIDTH='+(L '\[SRJ-EA\] LINEWIDTH'))
$r+=('LINEWIDTH_CLASSES_N='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] LINEWIDTH class="[^"]+"') | Measure-Object).Count))
$r+=('LINEWIDTH_TRUNC_NZ='+(((Select-String -LiteralPath $j -Pattern '\[SRJ-EA\] LINEWIDTH class="[^"]+" max=\d+ cap=\d+ truncated=([1-9]\d*)').Count)))
$r+=('DECISION_ROWS='+(C 'SLIMBR_DECISION rows='))
$r+=('SPOT_INPLAY='+(L 'INPLAYCOMMIT.*applied=1'))
$r+=('SPOT_XOBPROMO_N='+(C 'XOBPROMO '))
$r+=('SPOT_SWEPTMASK_N='+(C 'SWEPTMASK'))
$r | Set-Content -LiteralPath $out
Get-Content -LiteralPath $out
